export type Statut = "Disponible" | "En cours" | "Livré";

export interface GuideLie {
 titre: string;
 href: string;
}

export interface Annonce {
 slug: string;
 commune: string;
 departement: string;
 type: string;
 surfaceTerrain: number;
 surfaceHabitable: number;
 pieces: number;
 budget: number;
 statut: Statut;
 image: string;
 images: string[];
 accroche: string;
 description: string[];
 points: string[];
 zone: string;
 contexte: string;
 guidesLies: GuideLie[];
}

export const annonces: Annonce[] = [
 // --- Terrains issus du portefeuille partenaires fonciers ---
 {
 slug: "terrain-vulbens-407m2-clos-alizees",
 commune: "Vulbens",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 407,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 222600,
 statut: "Disponible",
 image: "/images/terrains/vulbens-407.jpg",
 images: ["/images/terrains/vulbens-407.jpg"],
 accroche: "407 m² viabilisé — Commerces, gare et TPG à pied — Frontière suisse",
 description: [
 "Lot à bâtir de 407 m² au sein d'un lotissement de 7 parcelles entièrement viabilisées à Vulbens (74520), à deux pas de la frontière suisse. L'emprise constructible maximale est de 184 m² au sol.",
 "Toutes les viabilités sont raccordées directement sur le terrain. Les commerces, les écoles, la gare et les bus TPG reliant Genève sont accessibles à pied depuis la parcelle — un atout rare dans le Genevois français.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner votre projet depuis l'étude de faisabilité jusqu'à la réception du chantier.",
 ],
 points: [
 "407 m² dans un lotissement de 7 lots viabilisés",
 "Emprise constructible : 184 m² au sol",
 "Commerces, gare et bus TPG accessibles à pied",
 "À deux pas de la frontière suisse",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Vulbens est une commune du Genevois français (74520) très appréciée des frontaliers pour sa proximité immédiate avec la Suisse et la qualité de son cadre de vie. L'accès aux transports en commun transfrontaliers depuis le village est un avantage déterminant. La zone sismique 3 s'applique — bureau d'études structure systématiquement intégré par M&M CONSTRUCTION.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 ],
 },
 {
 slug: "terrain-vulbens-588m2-clos-alizees",
 commune: "Vulbens",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 588,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 265300,
 statut: "Disponible",
 image: "/images/terrains/vulbens-588.jpg",
 images: ["/images/terrains/vulbens-588.jpg"],
 accroche: "588 m² viabilisé — Transports à pied — Proche frontière suisse",
 description: [
 "Lot de 588 m² au sein du même lotissement de 7 parcelles à Vulbens (74520), entièrement viabilisé. Une surface plus généreuse pour envisager un projet de maison familiale avec de beaux espaces extérieurs.",
 "Toutes les viabilités sont présentes sur le terrain. La situation du lotissement, à distance de marche de la gare, des commerces et des bus TPG, offre un confort de vie rare dans ce secteur très recherché du Genevois français.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "588 m² dans un lotissement de 7 lots viabilisés",
 "Toutes viabilités sur place",
 "Commerces, gare et bus TPG à pied",
 "Frontière suisse à deux pas",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Même lotissement que la parcelle de 407 m² à Vulbens (74520). La surface supérieure de ce lot permet d'envisager une villa avec jardin et terrasse de belle ampleur. Le secteur est classé en zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-feigeres-1394m2-projet-demolition",
 commune: "Feigères",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 1394,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 259000,
 statut: "Disponible",
 image: "/images/terrains/feigeres-1394.jpg",
 images: ["/images/terrains/feigeres-1394.jpg"],
 accroche: "1 394 m² en zone UB — Boisé avec ruisseau — Portes de Genève",
 description: [
 "Grande parcelle de 1 394 m² à Feigères (74160), aux portes de Genève, classée en zone UB. Le terrain boisé, en légère pente, traversé par un ruisseau, offre un cadre naturel préservé et rare dans ce secteur.",
 "La parcelle accueille actuellement une maison à démolir ainsi qu'une annexe. Un budget de démolition, de désamiantage éventuel et d'élagage est à intégrer dans l'enveloppe globale du projet — à évaluer précisément lors de l'étude de faisabilité. Le projet permettra la construction d'une maison individuelle, sous réserve des règles du PLU local.",
 ],
 points: [
 "1 394 m² en zone UB — construction d'une maison individuelle possible",
 "Terrain boisé en pente avec ruisseau — cadre naturel préservé",
 "Démolition de l'existant et désamiantage à prévoir (à chiffrer)",
 "Feigères (74160) — aux portes de Genève",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Feigères est une commune du Genevois français (74160) très appréciée pour son environnement calme et sa proximité avec Genève et Saint-Julien-en-Genevois. Ce type de grande parcelle boisée, avec bâtisse existante à démolir, constitue une opportunité de créer un projet sur-mesure dans un cadre naturel. Les coûts de démolition et d'éventuels travaux préalables sont à évaluer par des professionnels avant engagement. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 ],
 },
 {
 slug: "terrain-beaumont-573m2-hameau-travers",
 commune: "Beaumont",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 573,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 350000,
 statut: "Disponible",
 image: "/images/terrains/beaumont-573.jpg",
 images: ["/images/terrains/beaumont-573.jpg"],
 accroche: "573 m² — Vue dominante sur Genève — Hameau des Travers — Sentiers du Salève",
 description: [
 "Terrain de 573 m² dans le hameau des Travers à Beaumont (74160), bénéficiant d'une vue dominante sur Genève et le bassin genevois. La frontière suisse n'est qu'à quelques minutes, et les sentiers de randonnée du Salève sont accessibles depuis la parcelle.",
 "Un emplacement d'exception pour construire une villa en ossature bois tirant pleinement parti du panorama. La topographie du site et son exposition sont à analyser lors de l'étude de faisabilité afin d'optimiser l'orientation architecturale.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "573 m² dans le hameau des Travers à Beaumont",
 "Vue dominante sur Genève et le bassin genevois",
 "Quelques minutes de la frontière suisse",
 "Sentiers du Salève accessibles depuis la parcelle",
 "Etude de faisabilité M&M CONSTRUCTION sur demande",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Beaumont (74160) est une commune du Genevois français à mi-hauteur, connue pour ses vues panoramiques sur Genève. Le hameau des Travers est un secteur calme et résidentiel très recherché des frontaliers. Zone sismique 3 — bureau d'études structure intégré systématiquement.",
 guidesLies: [
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-presilly-661m2-viabilise",
 commune: "Présilly",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 661,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 370000,
 statut: "Disponible",
 image: "/images/terrains/presilly-661.jpg",
 images: ["/images/terrains/presilly-661.jpg"],
 accroche: "661 m² viabilisé — Secteur rare du Genevois français — Présilly (74160)",
 description: [
 "Terrain à bâtir de 661 m² entièrement viabilisé à Présilly (74160), dans le Genevois français. Les opportunités foncières constructibles sont rares dans ce secteur prisé par les frontaliers pour sa qualité de vie et sa position stratégique à proximité de la Suisse.",
 "La viabilisation complète du terrain simplifie les démarches et réduit les délais : les raccordements sont déjà en place, le permis de construire peut être déposé rapidement.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner votre projet de construction.",
 ],
 points: [
 "661 m² entièrement viabilisé",
 "Présilly (74160) — secteur rare du Genevois français",
 "Raccordements en place — dépôt de PC immédiatement possible",
 "Cadre calme et verdoyant à proximité de la Suisse",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Présilly est une commune du Genevois français (74160) à faible pression urbaine, ce qui rend les terrains constructibles particulièrement rares et recherchés. Proximité de Saint-Julien-en-Genevois et de la frontière suisse. Zone sismique 3.",
 guidesLies: [
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-neydens-770m2-viabilise",
 commune: "Neydens",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 770,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 360000,
 statut: "Disponible",
 image: "/images/terrains/neydens-770.jpg",
 images: ["/images/terrains/neydens-770.jpg"],
 accroche: "770 m² viabilisé — Vue montagnes — Frontière suisse à proximité — Neydens (74160)",
 description: [
 "Terrain à bâtir de 770 m² entièrement viabilisé à Neydens (74160), à proximité immédiate de la frontière suisse et bénéficiant d'une belle vue sur les montagnes environnantes. Les commerces sont accessibles rapidement depuis la parcelle.",
 "Neydens est l'une des communes les plus recherchées du Genevois français pour sa situation exceptionnelle entre Genève, Annecy et le massif du Salève. Un terrain rare dans ce secteur à haute demande foncière.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "770 m² entièrement viabilisé",
 "Vue sur les montagnes",
 "Frontière suisse à proximité immédiate",
 "Commerces accessibles rapidement",
 "Neydens (74160) — secteur très recherché",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Neydens (74160) est une commune particulièrement prisée du Genevois français, à la croisée des routes vers Genève, Annecy et le Salève. Le foncier y est sous forte tension et les terrains viabilisés à plus de 700 m² sont devenus très rares. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-saint-julien-378m2-cervonnex-plein-sud",
 commune: "Saint-Julien-en-Genevois",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 378,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 320000,
 statut: "Disponible",
 image: "/images/terrains/saint-julien-378.jpg",
 images: ["/images/terrains/saint-julien-378.jpg"],
 accroche: "378 m² plat plein sud — Cervonnex — École et commerces à 5 min — Accès Suisse immédiat",
 description: [
 "Terrain plat de 378 m², exposé plein sud, dans le hameau de Cervonnex, quartier de Saint-Julien-en-Genevois (74160). L'accès à la Suisse est quasi immédiat depuis ce secteur, idéal pour les frontaliers travaillant à Genève.",
 "L'exposition plein sud maximise les apports solaires passifs et le confort thermique de la future construction. École et commerces sont accessibles en 5 minutes. Un emplacement central dans le Genevois français.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "378 m² plat — exposition plein sud",
 "Hameau de Cervonnex — Saint-Julien-en-Genevois",
 "Accès à la Suisse quasi immédiat",
 "École et commerces à 5 minutes",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Saint-Julien-en-Genevois (74160) est la principale commune du Genevois français côté France, à 15 km de Genève. Le hameau de Cervonnex bénéficie d'une situation privilégiée avec un accès rapide à la frontière et un environnement résidentiel calme. Zone sismique 3 — bureau d'études structure systématiquement requis.",
 guidesLies: [
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-annemasse-740m2-pc-accepte",
 commune: "Annemasse",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 740,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 290000,
 statut: "Disponible",
 image: "/images/terrains/annemasse-740.jpg",
 images: ["/images/terrains/annemasse-740.jpg"],
 accroche: "740 m² plat arboré — PC accepté maison 135 m² + garage — Impasse calme — Tram à proximité",
 description: [
 "Terrain plat et arboré de 740 m², sans vis-à-vis, situé dans une impasse calme à Annemasse (74100), aux portes de Genève. Un permis de construire pour une maison de 135 m² avec garage a déjà été déposé et accepté sur cette parcelle — un gain de temps appréciable.",
 "La parcelle bénéficie de la proximité des transports en commun du réseau Grand Genève et sera desservie par le futur tramway. Environnement verdoyant et préservé, rare en secteur annemassien.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "740 m² plat et arboré — sans vis-à-vis",
 "PC accepté pour maison 135 m² + garage",
 "Impasse calme — aucune nuisance de transit",
 "Transports en commun et futur tram à proximité",
 "Annemasse (74100) — portes de Genève",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce terrain à Annemasse présente un avantage rare : un permis de construire déjà accepté, qui réduit significativement le délai avant démarrage du chantier. La situation dans une impasse garantit la tranquillité et l'absence de circulation de transit. Zone sismique 3 — bureau d'études structure intégré.",
 guidesLies: [
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-cranves-sales-715m2-lossy-viabilise",
 commune: "Cranves-Sales",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 715,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 319500,
 statut: "Disponible",
 image: "/images/terrains/cranves-sales-715.jpg",
 images: ["/images/terrains/cranves-sales-715.jpg"],
 accroche: "715 m² viabilisé — Vue dégagée — Hameau de Lossy — Cranves-Sales (74380)",
 description: [
 "Terrain à bâtir de 715 m² entièrement viabilisé dans le charmant hameau de Lossy à Cranves-Sales (74380). La parcelle bénéficie d'une belle vue dégagée sur les environs, avec toutes les viabilités raccordées directement sur le terrain.",
 "L'emprise constructible maximale autorisée est de 225 m² au sol — de quoi concevoir une maison familiale de belle ampleur avec des espaces extérieurs généreux. Cranves-Sales est une commune résidentielle prisée du Genevois français, à 10 minutes d'Annemasse et 20 minutes de Genève.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "715 m² entièrement viabilisé — vue dégagée",
 "Hameau de Lossy à Cranves-Sales",
 "Emprise constructible : 225 m² au sol",
 "Toutes viabilités raccordées sur la parcelle",
 "10 min Annemasse — 20 min Genève",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Le hameau de Lossy à Cranves-Sales (74380) est un secteur résidentiel calme, bien positionné dans le Genevois français. La commune est sous forte pression foncière due à la demande des frontaliers. Les terrains viabilisés avec vue sont particulièrement recherchés. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-cranves-sales-720m2-chemin-moulins",
 commune: "Cranves-Sales",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 720,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 249000,
 statut: "Disponible",
 image: "/images/terrains/cranves-sales-720.jpg",
 images: ["/images/terrains/cranves-sales-720.jpg"],
 accroche: "720 m² en zone UHp — Exposé Sud/Sud-Ouest — Proche Annemasse",
 description: [
 "Parcelle de 720 m² au Chemin des Moulins à Cranves-Sales (74380), classée en zone UHp, légèrement en pente et exposée Sud/Sud-Ouest pour un ensoleillement naturel optimal. L'emprise constructible est de 144 m², permettant une maison R+1 avec combles aménageables.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "720 m² en zone UHp — légèrement en pente",
 "Exposition Sud/Sud-Ouest — ensoleillement optimal",
 "Emprise constructible : 144 m² — R+1 avec combles possible",
 "Proche Annemasse et axes autoroutiers vers Genève",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Cranves-Sales (74380) est une commune résidentielle du Genevois français avec un accès rapide à Annemasse et à la frontière suisse. Le secteur du Chemin des Moulins bénéficie d'un environnement calme. Les terrains constructibles y sont rares et très demandés. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-cranves-sales-615m2-lossy-reseaux-proximite",
 commune: "Cranves-Sales",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 615,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 298000,
 statut: "Disponible",
 image: "/images/terrains/cranves-sales-615.jpg",
 images: ["/images/terrains/cranves-sales-615.jpg"],
 accroche: "615 m² — Vue Voirons et Salève — Transports 3 min — Gare Annemasse 6 min",
 description: [
 "Terrain de 615 m² dans le hameau de Lossy à Cranves-Sales (74380), offrant une belle vue sur les Voirons et le Salève. Non viabilisé, les réseaux sont disponibles à proximité immédiate de la parcelle — le raccordement est à prévoir dans le budget.",
 "Le terrain accueille une petite construction existante. Les transports en commun avec parking relais sont à 3 minutes, la gare d'Annemasse à 6 minutes en voiture, et l'ensemble des commodités de l'agglomération annemassienne est accessible rapidement.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "615 m² avec vue sur les Voirons et le Salève",
 "Hameau de Lossy — cadre calme et verdoyant",
 "Réseaux à proximité immédiate (viabilisation à prévoir)",
 "Transports en commun avec PR à 3 minutes",
 "Gare d'Annemasse à 6 minutes en voiture",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce terrain de Cranves-Sales (74380) présente la particularité de ne pas être encore viabilisé, ce qui justifie un prix inférieur aux parcelles équivalentes raccordées. Les réseaux étant à proximité immédiate, le coût de raccordement reste limité. À intégrer dans le budget global avec une estimation précise lors de l'étude de faisabilité. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 ],
 },
 {
 slug: "terrain-neydens-782m2-la-forge",
 commune: "Neydens",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 782,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 360000,
 statut: "Disponible",
 image: "/images/terrains/neydens-782.jpg",
 images: ["/images/terrains/neydens-782.jpg"],
 accroche: "782 m² plein sud/ouest — Lotissement La Forge — Entièrement viabilisé — Neydens (74160)",
 description: [
 "Terrain de 782 m² au sein d'un lotissement de 4 parcelles à Neydens (74160), secteur La Forge. Exposition idéale plein sud et plein ouest, garantissant un ensoleillement optimal tout au long de la journée.",
 "Entièrement viabilisé et raccordé à tous les réseaux (électricité, eau potable, eaux usées, eaux pluviales). La configuration de la parcelle permet d'envisager la construction d'une ou deux habitations individuelles ou mitoyennes, avec de généreux espaces extérieurs.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "782 m² dans le lotissement La Forge à Neydens",
 "Exposition plein sud et ouest — ensoleillement optimal",
 "Entièrement viabilisé — tous réseaux raccordés",
 "1 ou 2 habitations envisageables selon le PLU",
 "Neydens (74160) — Genevois français",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Le lotissement La Forge à Neydens (74160) est un projet de 4 lots bien exposés dans une commune très recherchée du Genevois français. La viabilisation complète et l'exposition plein sud/ouest constituent deux atouts majeurs pour la qualité de vie future. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-neydens-831m2-la-forge",
 commune: "Neydens",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 831,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 375000,
 statut: "Disponible",
 image: "/images/terrains/neydens-831.jpg",
 images: ["/images/terrains/neydens-831.jpg"],
 accroche: "831 m² plein sud/ouest — Lotissement La Forge — Viabilisé — Surface généreuse",
 description: [
 "Parcelle de 831 m² dans le même lotissement La Forge à Neydens (74160), offrant une surface encore plus généreuse pour concevoir un projet ambitieux. Exposition plein sud et ouest pour un ensoleillement optimal, entièrement viabilisée et raccordée à tous les réseaux.",
 "La configuration de cette grande parcelle permet d'envisager une villa spacieuse avec jardins paysagés et espaces extérieurs de qualité, tout en conservant la possibilité d'une habitation mitoyenne selon le projet.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "831 m² — surface généreuse pour un grand projet",
 "Lotissement La Forge à Neydens — 4 lots au total",
 "Exposition plein sud et ouest",
 "Entièrement viabilisé — tous réseaux raccordés",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Plus grande parcelle du lotissement La Forge à Neydens (74160). La surface de 831 m² permet d'envisager une villa avec jardin et terrasse de belle envergure. Même cadre d'exception que les autres lots du lotissement. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-vetraz-monthoux-462m2-viabilise",
 commune: "Vétraz-Monthoux",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 462,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 225000,
 statut: "Disponible",
 image: "/images/terrains/vetraz-monthoux-462.jpg",
 images: ["/images/terrains/vetraz-monthoux-462.jpg"],
 accroche: "462 m² constructible — Portes de Genève — Résidentiel calme — Vétraz-Monthoux (74100)",
 description: [
 "Terrain constructible de 462 m² à Vétraz-Monthoux (74100), aux portes de Genève, dans un environnement résidentiel calme entre lac et montagnes. La viabilisation sera réalisée par l'acquéreur lors du dépôt du permis de construire.",
 "Vétraz-Monthoux est une commune recherchée pour la qualité de vie qu'elle offre à ses habitants : accès rapide à la Suisse et aux zones d'emploi genevoises, commerces, écoles et infrastructures sportives de proximité. Deux terrains constructibles sont disponibles sur ce secteur.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "462 m² constructible à Vétraz-Monthoux",
 "Viabilisation lors du dépôt du permis de construire",
 "Accès rapide à la Suisse et aux zones d'emploi genevoises",
 "Commerces, écoles, équipements sportifs à proximité",
 "Cadre résidentiel calme — entre lac et montagnes",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Vétraz-Monthoux (74100) fait partie de l'agglomération d'Annemasse, à moins de 15 minutes de Genève. La commune est appréciée pour son cadre résidentiel verdoyant et sa proximité avec la frontière suisse. Le fait que la viabilisation soit à la charge de l'acquéreur se reflète dans le prix de la parcelle. Zone sismique 3.",
 guidesLies: [
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-vetraz-monthoux-863m2-secteur-mairie",
 commune: "Vétraz-Monthoux",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 863,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 405000,
 statut: "Disponible",
 image: "/images/terrains/vetraz-monthoux-863.jpg",
 images: ["/images/terrains/vetraz-monthoux-863.jpg"],
 accroche: "863 m² — Zone UH4 — CES 0,2 — 172 m² de plancher — Viabilisé — Secteur Mairie",
 description: [
 "Rare à la vente : terrain de 863 m² sur le côteau de Vétraz-Monthoux (74100), secteur Mairie, dans un cadre agréable et très recherché. Zone UH4, coefficient d'emprise au sol de 0,2 permettant une surface plancher de 172 m².",
 "Entièrement viabilisé. L'exposition plein sud garantit un ensoleillement optimal — un avantage bioclimatique majeur pour optimiser les apports solaires passifs et réduire les besoins énergétiques futurs.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "863 m² — zone UH4 — CES 0,2",
 "Surface plancher autorisée : 172 m²",
 "Entièrement viabilisé",
 "Exposition plein sud — apports solaires optimaux",
 "Secteur Mairie — Vétraz-Monthoux (74100)",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce terrain du secteur Mairie à Vétraz-Monthoux représente une opportunité rare par sa taille (863 m²) et sa situation dans l'une des zones résidentielles les plus prisées de la commune. La zone UH4 avec CES 0,2 permet une belle surface plancher tout en conservant de larges espaces extérieurs. Zone sismique 3 — bureau d'études structure intégré.",
 guidesLies: [
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-dingy-vuache-454m2-hameau-fleur-or",
 commune: "Dingy-en-Vuache",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 454,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 215000,
 statut: "Disponible",
 image: "/images/terrains/dingy-454.jpg",
 images: ["/images/terrains/dingy-454.jpg"],
 accroche: "454 m² viabilisé — Le Hameau de la fleur d'Or — 30 min Genève",
 description: [
 "Terrain viabilisé de 454 m² dans le lotissement 'Le Hameau de la fleur d'Or' à Dingy-en-Vuache (74520), petite commune calme et sécurisée de Haute-Savoie. Raccordé aux réseaux d'eau potable, assainissement, électricité et télécom. Desservi par une voirie principale aménagée.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "454 m² viabilisé dans le lotissement Le Hameau de la fleur d'Or",
 "Raccordé à tous les réseaux — voirie aménagée",
 "20 min Saint-Julien-en-Genevois — 30 min Genève",
 "Cadre verdoyant et bucolique",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Dingy-en-Vuache (74520) est une petite commune de Haute-Savoie offrant un cadre de vie préservé, idéal pour les frontaliers souhaitant s'éloigner de l'agitation de l'agglomération annemassienne tout en restant à bonne distance de Genève. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-presilly-681m2-vue-degagee",
 commune: "Présilly",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 681,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 390000,
 statut: "Disponible",
 image: "/images/terrains/presilly-681.jpg",
 images: ["/images/terrains/presilly-681.jpg"],
 accroche: "681 m² — Vue dégagée — Calme et verdoyant — Proche frontière suisse — Présilly (74160)",
 description: [
 "Beau terrain de 681 m² à Présilly (74160), dans un cadre calme et verdoyant, avec une vue dégagée sur les environs. Le lotissement sera desservi par un accès existant et raccordé aux réseaux existants — une mise en œuvre facilitée.",
 "À proximité de la frontière suisse, des axes de circulation et de l'ensemble des commodités du secteur genevois. Présilly est une commune très appréciée pour la qualité de vie qu'elle offre, à l'écart de l'agitation urbaine tout en restant proche de Genève.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "681 m² avec vue dégagée",
 "Cadre calme et verdoyant à Présilly (74160)",
 "Lotissement raccordé aux réseaux existants",
 "Proche de la frontière suisse et des axes de circulation",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Présilly (74160) est une commune rurale du Genevois français à faible pression urbaine, idéale pour les familles cherchant à construire dans un cadre naturel préservé tout en restant à proximité de Genève. Le foncier y est rare. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-viry-626m2-malagny",
 commune: "Viry",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 626,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 320000,
 statut: "Disponible",
 image: "/images/terrains/viry-626.jpg",
 images: ["/images/terrains/viry-626.jpg"],
 accroche: "626 m² viabilisé — Secteur Malagny — Viry (74580) — Une seule habitation — Belle opportunité",
 description: [
 "Terrain de 626 m² issu d'une division parcellaire dans le secteur recherché de Malagny à Viry (74580). Les viabilités sont disponibles à proximité. La parcelle permet la construction d'une seule habitation individuelle — une configuration idéale pour un projet familial sur-mesure.",
 "Viry est une commune du Genevois français très appréciée pour son cadre résidentiel calme, à bonne distance de la frontière suisse. Le secteur de Malagny est particulièrement recherché. Une belle opportunité à saisir rapidement sur ce secteur.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "626 m² issu d'une division parcellaire",
 "Secteur Malagny — Viry (74580)",
 "Viabilités disponibles à proximité",
 "Construction d'une habitation individuelle",
 "Secteur très recherché du Genevois français",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Viry (74580) est une commune du Genevois français appréciée pour son environnement résidentiel calme. Le secteur de Malagny est l'un des plus recherchés de la commune. La division parcellaire récente garantit la constructibilité du terrain sous réserve de vérification du PLU. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 ],
 },
 {
 slug: "terrain-archamps-466m2-ces-02",
 commune: "Archamps",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 466,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 270000,
 statut: "Disponible",
 image: "/images/terrains/archamps-466.jpg",
 images: ["/images/terrains/archamps-466.jpg"],
 accroche: "466 m² — 5 min frontière suisse — 20 min Genève — CES 0,2",
 description: [
 "Terrain de 466 m² à Archamps (74160), sur les hauteurs, dans un quartier résidentiel calme. À seulement 5 minutes de la frontière suisse et 20 minutes du centre de Genève et de l'aéroport international — une localisation privilégiée pour les frontaliers.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "466 m² — CES 0,2",
 "5 min frontière suisse — 20 min Genève et aéroport",
 "Sur les hauteurs d'Archamps — quartier résidentiel calme",
 "Viabilisation à prévoir (réseaux à proximité)",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Archamps (74160) est une commune stratégique du Genevois français, connue pour son technopôle et son accès direct à Genève en 10-20 minutes. Ce terrain sur les hauteurs offre une implantation calme avec les avantages de proximité d'Archamps. Zone sismique 3 — bureau d'études structure requis. M&M CONSTRUCTION intervient régulièrement sur la commune.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-archamps-822m2-hauteurs",
 commune: "Archamps",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 822,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 320000,
 statut: "Disponible",
 image: "/images/terrains/archamps-822.jpg",
 images: ["/images/terrains/archamps-822.jpg"],
 accroche: "822 m² — 5 min frontière suisse — Quartier calme — CES 0,2 — Grande surface",
 description: [
 "Belle parcelle de 822 m² à Archamps (74160), sur les hauteurs, dans un quartier résidentiel calme. Même secteur que la parcelle de 466 m², avec une surface généreusement plus grande permettant un projet de villa contemporaine avec jardins.",
 "À 5 minutes de la frontière suisse et 20 minutes du centre de Genève et de l'aéroport. coefficient d'emprise au sol de 0,20. Les viabilités sont à prévoir, les réseaux étant disponibles à proximité.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "822 m² — surface généreuse pour un grand projet",
 "CES 0,2",
 "5 min frontière suisse — 20 min Genève et aéroport",
 "Quartier résidentiel calme sur les hauteurs d'Archamps",
 "Viabilisation à prévoir (réseaux à proximité)",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Archamps (74160) bénéficie d'un accès exceptionnel à Genève et à son aéroport. Ce terrain de 822 m² sur les hauteurs offre de l'espace et du calme dans une commune dynamique du Genevois français. Zone sismique 3 — bureau d'études structure intégré dans tous les projets M&M CONSTRUCTION sur la commune.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-savigny-670m2-pres-colombiers",
 commune: "Savigny",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 670,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 199500,
 statut: "Disponible",
 image: "/images/terrains/savigny-670.jpg",
 images: ["/images/terrains/savigny-670.jpg"],
 accroche: "670 m² plat viabilisé — Lotissement Les Prés Colombiers — Vue massifs — Permis déposable immédiatement",
 description: [
 "Terrain plat de 670 m² dans le lotissement 'Les Prés Colombiers' à Savigny (74520), composé de 4 lots de 609 à 693 m². Magnifique terrain plat en bordure agricole, offrant une vue dégagée sur les massifs environnants. Terrains viabilisés et libres constructeurs.",
 "Le permis de construire peut être déposé immédiatement. Un environnement naturel préservé, parfait pour les amoureux de nature souhaitant construire dans un cadre authentique tout en restant proche de Genève.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "670 m² plat dans le lotissement Les Prés Colombiers",
 "Vue dégagée sur les massifs environnants",
 "Viabilisé et ",
 "Permis de construire déposable immédiatement",
 "Cadre naturel préservé — Savigny (74520)",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Savigny est une commune de Haute-Savoie (74520) offrant un cadre de vie authentique et préservé dans le chef-lieu de commune. Le lotissement Les Prés Colombiers est un projet de 4 lots entièrement viabilisés permettant de construire rapidement. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-vers-640m2-vue-jet-eau-geneve",
 commune: "Vers",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 640,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 230000,
 statut: "Disponible",
 image: "/images/terrains/vers-640.jpg",
 images: ["/images/terrains/vers-640.jpg"],
 accroche: "640 m² viabilisé — Vue sur le jet d'eau de Genève — 115 m² au sol",
 description: [
 "Terrain entièrement viabilisé de 640 m² à Vers (74160), en limite de village. La parcelle offre une vue remarquable sur le jet d'eau de Genève, dans un secteur agréable et bucolique.",
 "La possibilité de construire une surface au sol de 115 m² permet d'envisager une belle maison de plain-pied ou un projet à étage. Raccordé à tous les réseaux, y compris à l'égout. À découvrir rapidement dans ce secteur aux opportunités rares.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "640 m² entièrement viabilisé — raccordé à l'égout",
 "Vue sur le jet d'eau de Genève",
 "Surface constructible au sol : 115 m²",
 "Vers (74160) — Genevois français",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Vers est une commune du Genevois français (74160) offrant un cadre de vie bucolique avec des vues exceptionnelles vers le lac Léman et Genève. Ce type de terrain viabilisé avec vue est une opportunité rare dans ce secteur. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },
 {
 slug: "terrain-dingy-vuache-835m2-hameau-fleur-or",
 commune: "Dingy-en-Vuache",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 835,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 345000,
 statut: "Disponible",
 image: "/images/hero-maison-bois-montagne-1.jpg",
 images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-extension-bois-jardin.jpg"],
 accroche: "835 m² viabilisé — Le Hameau de la fleur d'Or — 30 min Genève",
 description: [
 "Terrain viabilisé de 835 m² dans le lotissement 'Le Hameau de la fleur d'Or' à Dingy-en-Vuache (74520), idéalement situé pour les travailleurs locaux et frontaliers. Raccordé à tous les réseaux et desservi par une voirie principale aménagée.",
 "La surface généreuse de cette parcelle permet d'envisager une villa familiale avec de beaux espaces extérieurs. À 30 minutes de Genève et dans un cadre verdoyant et calme typique de la Haute-Savoie.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "835 m² — grande surface dans Le Hameau de la fleur d'Or",
 "Viabilisé — tous réseaux raccordés",
 "30 minutes de Genève — cadre verdoyant",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Le lotissement 'Le Hameau de la fleur d'Or' à Dingy-en-Vuache (74520) propose plusieurs lots dont cette grande parcelle de 835 m². Dingy-en-Vuache offre un cadre naturel préservé à distance raisonnable de Genève. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-dingy-vuache-568m2-ces30",
 commune: "Dingy-en-Vuache",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 568,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 240000,
 statut: "Disponible",
 image: "/images/terrains/dingy-568.jpg",
 images: ["/images/terrains/dingy-568.jpg"],
 accroche: "568 m² — CES 30 % — Emprise 170 m² — Viabilités en bordure",
 description: [
 "Parcelle à bâtir de 568 m² à Dingy-en-Vuache (74520), avec un coefficient d'emprise au sol de 30 %, permettant une surface au sol maximale de 170 m². Les viabilités sont disponibles en bordure de terrain — le raccordement est donc réalisable.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "568 m² — CES 30 % — emprise au sol 170 m²",
 "Viabilités en bordure — raccordement possible",
 "Dingy-en-Vuache (74520) — Haute-Savoie",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce terrain à Dingy-en-Vuache présente l'avantage d'un CES de 30 %, légèrement supérieur à la moyenne du secteur, permettant une emprise au sol généreuse de 170 m² sur 568 m². Les viabilités en bordure facilitent le raccordement. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 ],
 },
 {
 slug: "terrain-vulbens-424m2-maison-jumelee",
 commune: "Vulbens",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 424,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 235000,
 statut: "Disponible",
 image: "/images/hero-maison-bois-montagne-2.jpg",
 images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-maison-bois-alpine.jpg"],
 accroche: "424 m² plat viabilisé — Maison jumelée 250 m² SP — Lotissement — Vulbens (74520)",
 description: [
 "Lot de 424 m² dans un lotissement à Vulbens (74520), terrain plat et entièrement viabilisé. La configuration réglementaire du lotissement est prévue pour une maison jumelée avec une surface de plancher autorisée de 250 m² — idéale pour un projet en duo ou une famille cherchant un grand espace habitable.",
 "Proche de la frontière suisse, dans un secteur bien desservi par les transports transfrontaliers. Vulbens est une commune calme du Genevois français, très appréciée pour sa qualité de vie.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "424 m² plat et viabilisé dans un lotissement",
 "Maison jumelée — surface de plancher 250 m²",
 "Proche frontière suisse — transports transfrontaliers",
 "Vulbens (74520) — commune calme du Genevois français",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce lot de Vulbens (74520) est destiné à une maison jumelée, une formule permettant de réduire le coût foncier à la surface habitable tout en conservant un terrain de 424 m². La commune est idéalement positionnée aux portes de la Suisse. Zone sismique 3.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
 ],
 },
 {
 slug: "terrain-collonges-sous-saleve-1053m2-zone-ud",
 commune: "Collonges-sous-Salève",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 1053,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 572000,
 statut: "Disponible",
 image: "/images/terrains/collonges-1053.jpg",
 images: ["/images/terrains/collonges-1053.jpg"],
 accroche: "1 053 m² zone UD — CES 0,25 — Exposition sud-ouest — Douane 5 min — Genève 20 min",
 description: [
 "Emplacement privilégié pour frontaliers : terrain de 1 053 m² à Collonges-sous-Salève (74160), à quelques minutes de la frontière suisse. Classé en zone UD avec un coefficient d'emprise au sol de 0,25, la parcelle permet un projet résidentiel harmonieux dans un environnement pavillonnaire verdoyant.",
 "Exposition sud-ouest pour un ensoleillement optimal et une belle vue dégagée sur les alentours. Les raccordements aux réseaux sont accessibles en bordure de parcelle. Douane de Croix-de-Rozon à 5 minutes, Genève accessible en 20 minutes. Les commerces, écoles et services se trouvent à proximité immédiate.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
 ],
 points: [
 "1 053 m² — zone UD — CES 0,25",
 "Exposition sud-ouest — belle vue dégagée",
 "Raccordements en bordure de parcelle",
 "Douane Croix-de-Rozon à 5 min — Genève à 20 min",
 "Commerces, écoles et services à proximité",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Collonges-sous-Salève (74160) est une commune très prisée des frontaliers, adossée au massif du Salève et à quelques minutes de la frontière suisse. La zone UD avec CES 0,25 permet une emprise au sol d'environ 263 m² sur cette parcelle de 1 053 m², laissant de larges espaces extérieurs. Zone sismique 3 — bureau d'études structure intégré systématiquement par M&M CONSTRUCTION.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
 ],
 },
 {
 slug: "terrain-collonges-sous-saleve-1096m2-vue-leman",
 commune: "Collonges-sous-Salève",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 1096,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 475000,
 statut: "Disponible",
 image: "/images/terrains/collonges-1096.jpg",
 images: ["/images/terrains/collonges-1096.jpg"],
 accroche: "1 096 m² — Vue sur le Jura, le Salève et le Lac Léman — Cadre calme et préservé",
 description: [
 "Terrain de 1 096 m² à Collonges-sous-Salève (74160), offrant une vue dégagée remarquable sur le Jura, le massif du Salève et le Lac Léman. Un panorama exceptionnel dans un environnement calme et préservé.",
 "Collonges-sous-Salève est une commune très appréciée des frontaliers pour la qualité de vie qu'elle offre, à bonne distance de Genève. Une rare opportunité sur ce secteur prisé, aux portes de la Suisse.",
 "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner votre projet depuis l'étude de faisabilité jusqu'à la réception du chantier.",
 ],
 points: [
 "1 096 m² — vue sur Jura, Salève et Lac Léman",
 "Cadre calme et préservé",
 "Collonges-sous-Salève (74160) — portes de la Suisse",
 "Commune très prisée des frontaliers",
 "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce terrain de Collonges-sous-Salève (74160) se distingue par son triple panorama sur le Jura, le Salève et le Lac Léman — une vue d'exception rare dans ce secteur. La commune est l'une des plus recherchées du Genevois français. Zone sismique 3 — bureau d'études structure systématiquement requis.",
 guidesLies: [
 { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 // ── Bonne (74380) ──────────────────────────────────────────────────────────

 {
 slug: "terrain-bonne-719m2-bonne-sur-menoge",
 commune: "Bonne",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 719,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 200000,
 statut: "Disponible",
 image: "/images/terrains/bonne-719.jpg",
 images: ["/images/terrains/bonne-719.jpg"],
 accroche: "719 m² zone UB — Bonne-sur-Ménoge (74380) — 15 min Annemasse",
 description: [
  "Terrain à bâtir de 719 m² en zone UB à Bonne (74380), commune de la vallée du Ménoge à 15 minutes d'Annemasse et 35 minutes d'Annecy. Accès direct à l'axe autoroutier A40, idéal pour les actifs du bassin genevois.",
  "La configuration de la parcelle et les règles de la zone UB permettent d'envisager une surface de plancher d'environ 165 m². Toutes les viabilités (eau, assainissement collectif, électricité, télécoms) sont disponibles en limite de parcelle ou à faible distance.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION accompagne votre projet dès l'étude de faisabilité jusqu'à la réception du chantier.",
 ],
 points: [
  "719 m² — zone UB — Bonne (74380)",
  "Surface de plancher estimée : ~165 m²",
  "Assainissement collectif — viabilités en bordure",
  "Accès A40 — 15 min Annemasse, 35 min Annecy",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Bonne est une commune rurale de la vallée du Ménoge (74380) bien desservie par l'axe autoroutier A40. Le secteur offre un cadre de vie calme avec des prix fonciers encore accessibles par rapport à l'agglomération annemassienne. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-bonne-849m2-libre-constructeur",
 commune: "Bonne",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 849,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 240000,
 statut: "Disponible",
 image: "/images/terrains/bonne-849.jpg",
 images: ["/images/terrains/bonne-849.jpg"],
 accroche: "849 m² libre constructeur — Faible pente — Bonne (74380)",
 description: [
  "Terrain à bâtir de 849 m² à Bonne (74380), en légère pente, libre de tout constructeur. Toutes les viabilités sont disponibles en limite de parcelle : eau potable, eaux usées, électricité, télécoms et eaux pluviales.",
  "La surface et la configuration de la parcelle permettent de concevoir une maison individuelle de 170 à 190 m² de surface de plancher selon l'emprise retenue. Environnement calme, secteur résidentiel.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut coordonner l'ensemble de votre projet de construction dès la première consultation.",
 ],
 points: [
  "849 m² — légère pente — Bonne (74380)",
  "Libre de tout constructeur",
  "Toutes viabilités en limite de parcelle",
  "Surface de plancher estimée : ~190 m²",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ce terrain de Bonne (74380) se distingue par sa configuration généreuse et ses viabilités complètes en bordure, ce qui limite les frais de raccordement. Commune à 15 min d'Annemasse sur l'axe A40. Zone sismique 3 — bureau d'études structure requis.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-bonne-800m2-arboree",
 commune: "Bonne",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 800,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 235000,
 statut: "Disponible",
 image: "/images/terrains/bonne-800.jpg",
 images: ["/images/terrains/bonne-800.jpg"],
 accroche: "800 m² arboré — Libre constructeur — Bonne (74380)",
 description: [
  "Terrain de 800 m² à Bonne (74380), au cœur d'un secteur verdoyant et calme. La parcelle arborée bénéficie d'un cadre naturel préservé tout en restant à proximité des axes de desserte principaux. Libre de tout constructeur.",
  "La surface et la zone constructible permettent d'envisager une maison individuelle de bonne superficie. Idéal pour un projet de maison en ossature bois souhaitant s'intégrer harmonieusement dans l'environnement végétal existant.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION accompagne votre projet de la conception jusqu'à la réception.",
 ],
 points: [
  "800 m² — terrain arboré et verdoyant — Bonne (74380)",
  "Libre de tout constructeur",
  "Cadre naturel calme et préservé",
  "Proximité axes A40 — Faucigny",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Cette parcelle de Bonne (74380) offre un environnement naturel rare en secteur résidentiel. La végétation existante peut être intégrée au projet architectural pour un résultat bioclimatique optimal. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-bonne-800m2-piscine",
 commune: "Bonne",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 800,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 265000,
 statut: "Disponible",
 image: "/images/terrains/bonne-800-piscine.jpg",
 images: ["/images/terrains/bonne-800-piscine.jpg"],
 accroche: "800 m² avec piscine 12×5 existante — Pool house aménagé — Bonne (74380)",
 description: [
  "Terrain à bâtir de 800 m² à Bonne (74380) livré avec une piscine de 12×5 m déjà réalisée et un pool house aménagé. Un équipement rare et coûteux déjà inclus dans le prix du foncier, qui représente une économie significative sur le coût total du projet.",
  "La parcelle est parfaitement adaptée à la construction d'une maison individuelle, les aménagements extérieurs existants étant déjà en place. Secteur calme, proche des commodités de Bonne.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner la conception et la coordination de votre future maison sur ce terrain.",
 ],
 points: [
  "800 m² — Bonne (74380)",
  "Piscine 12×5 m déjà réalisée",
  "Pool house aménagé inclus",
  "Aménagements extérieurs existants — économie significative",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Rares sont les terrains livrés avec une piscine déjà construite et un pool house opérationnel. Ce bien de Bonne (74380) représente une opportunité pour les acheteurs souhaitant disposer d'un espace extérieur complet sans les délais et surcoûts liés à ces travaux. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Reignier-Ésery (74930) ─────────────────────────────────────────────────

 {
 slug: "terrain-reignier-esery-608m2-champetre",
 commune: "Reignier-Ésery",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 608,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 260000,
 statut: "Disponible",
 image: "/images/terrains/reignier-608.jpg",
 images: ["/images/terrains/reignier-608.jpg"],
 accroche: "608 m² — Cadre champêtre — Reignier-Ésery (74930)",
 description: [
  "Terrain à bâtir de 608 m² à Reignier-Ésery (74930), dans un environnement verdoyant et champêtre. Commune du Genevois français à 15 minutes d'Annemasse et 30 minutes de Genève, idéalement placée pour les travailleurs frontaliers.",
  "La parcelle, en zone constructible, permet d'envisager une maison individuelle d'environ 120 à 150 m² selon les règles du PLU local. Environnement calme et dégagé, éloigné du bruit et de la densité urbaine.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION accompagne votre projet dès l'analyse du PLU jusqu'à la réception du chantier.",
 ],
 points: [
  "608 m² — cadre champêtre — Reignier-Ésery (74930)",
  "15 min Annemasse, 30 min Genève",
  "Zone constructible — maison individuelle possible",
  "Environnement calme et dégagé",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Reignier-Ésery (74930) est une commune du Genevois français appréciée pour son cadre de vie rural, à bonne distance des centres urbains. Le marché foncier y reste plus accessible que dans les communes de première couronne genevoise. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-reignier-esery-839m2-proche-centre",
 commune: "Reignier-Ésery",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 839,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 230000,
 statut: "Disponible",
 image: "/images/terrains/reignier-839.jpg",
 images: ["/images/terrains/reignier-839.jpg"],
 accroche: "839 m² — Proche centre et commerces — Reignier-Ésery (74930)",
 description: [
  "Terrain à bâtir de 839 m² à Reignier-Ésery (74930), à proximité immédiate du centre-bourg, de ses commerces et de la gare. Une surface généreuse avec toutes les commodités à pied, dans une commune bien desservie du Genevois français.",
  "La configuration de la parcelle et la zone de constructibilité permettent d'envisager une maison individuelle spacieuse. Secteur résidentiel calme, à quelques minutes seulement des principaux axes routiers vers Annemasse et Genève.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut piloter votre projet de la conception jusqu'à la remise des clés.",
 ],
 points: [
  "839 m² — proche centre-bourg, commerces et gare",
  "Reignier-Ésery (74930) — Genevois français",
  "15 min Annemasse, 30 min Genève",
  "Secteur résidentiel — tous services à proximité",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Reignier-Ésery bénéficie d'une gare ferroviaire qui dessert Annemasse et le réseau transfrontalier. Ce terrain de 839 m² proche du centre représente une opportunité rare à ce prix dans le Genevois français. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Ayse (74130) ───────────────────────────────────────────────────────────

 {
 slug: "terrain-ayse-1245m2-coteaux-ensoleilles",
 commune: "Ayse",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 1245,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 270000,
 statut: "Disponible",
 image: "/images/terrains/ayse-1245.jpg",
 images: ["/images/terrains/ayse-1245.jpg"],
 accroche: "1 245 m² viabilisé — Coteaux ensoleillés — Ayse (74130)",
 description: [
  "Terrain à bâtir de 1 245 m² entièrement viabilisé sur les coteaux ensoleillés d'Ayse (74130), en légère pente. Une surface généreuse dans un secteur résidentiel privilégié de la vallée de l'Arve, à proximité de Bonneville et des commodités.",
  "La zone (UB, CES 0,20) autorise une emprise au sol d'environ 249 m², permettant de concevoir une maison individuelle de belle taille avec des espaces extérieurs généreux. Viabilités complètes en limite de parcelle.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION accompagne votre projet depuis l'analyse du PLU jusqu'à la remise des clés.",
 ],
 points: [
  "1 245 m² entièrement viabilisé — Ayse (74130)",
  "Coteaux ensoleillés — légère pente",
  "Zone UB, CES 0,20 — emprise ~249 m²",
  "Secteur résidentiel privilégié — vallée de l'Arve",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Ayse (74130) est une commune dynamique de la vallée de l'Arve, à 5 km de Bonneville et 30 km de Genève. Les coteaux exposés au soleil offrent des conditions idéales pour une maison bioclimatique orientée plein sud. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 // ── Étaux (74800) ──────────────────────────────────────────────────────────

 {
 slug: "terrain-etaux-800m2-vue-degagee",
 commune: "Étaux",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 800,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 215000,
 statut: "Disponible",
 image: "/images/terrains/etaux-800.jpg",
 images: ["/images/terrains/etaux-800.jpg"],
 accroche: "800 m² vue dégagée — Secteur calme — Étaux (74800)",
 description: [
  "Terrain à bâtir de 800 m² avec vue dégagée à Étaux (74800), commune calme du Faucigny à proximité de La Roche-sur-Foron. Un cadre préservé, éloigné des nuisances, avec un bel ensoleillement.",
  "La surface de la parcelle permet d'envisager une maison individuelle généralement de l'ordre de 120 à 160 m² de surface de plancher selon les règles du PLU local. Accès facile aux commodités de La Roche-sur-Foron à moins de 10 minutes.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut vous accompagner à chaque étape de votre projet de construction.",
 ],
 points: [
  "800 m² — vue dégagée — Étaux (74800)",
  "Secteur calme et préservé",
  "Proximité La Roche-sur-Foron — moins de 10 min",
  "Exposition favorable — ensoleillement optimal",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Étaux (74800) est un village du Faucigny entre La Roche-sur-Foron et Saint-Jeoire, appréciable pour son calme et son cadre verdoyant. Une alternative accessible aux communes plus urbanisées du secteur. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Amancy (74800) ─────────────────────────────────────────────────────────

 {
 slug: "terrain-amancy-644m2-centre-village",
 commune: "Amancy",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 644,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 199000,
 statut: "Disponible",
 image: "/images/terrains/amancy-644.jpg",
 images: ["/images/terrains/amancy-644.jpg"],
 accroche: "644 m² zone UC — Cœur d'Amancy — Double unité possible",
 description: [
  "Terrain à bâtir de 644 m² en zone UC au cœur du village d'Amancy (74800), à 10 minutes de La Roche-sur-Foron. La zone UC et la surface de la parcelle ouvrent la possibilité de réaliser deux unités d'habitation mitoyennes ou séparées — une opportunité rare en centre-village.",
  "Situation centrale avec accès facile à pied aux services de proximité. La commune d'Amancy, calme et bien desservie, offre un cadre de vie apprécié dans le Faucigny.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut étudier avec vous la faisabilité d'un ou deux logements sur cette parcelle.",
 ],
 points: [
  "644 m² zone UC — centre-bourg d'Amancy (74800)",
  "Double unité d'habitation possible",
  "10 min La Roche-sur-Foron",
  "Accès à pied aux commerces et services",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "La zone UC d'Amancy autorise une densité de construction supérieure aux zones UB ou UA classiques. Ce terrain de 644 m² en centre-bourg est particulièrement adapté à un projet de maison avec logement locatif ou à une division en deux lots. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── La Roche-sur-Foron (74800) ─────────────────────────────────────────────

 {
 slug: "terrain-la-roche-sur-foron-660m2-impasse-soleil",
 commune: "La Roche-sur-Foron",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 660,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 278000,
 statut: "Disponible",
 image: "/images/terrains/la-roche-sur-foron-660.jpg",
 images: ["/images/terrains/la-roche-sur-foron-660.jpg"],
 accroche: "660 m² permis purgé — Vue dégagée plein soleil — La Roche-sur-Foron (74800)",
 description: [
  "Terrain à bâtir de 660 m² à La Roche-sur-Foron (74800), situé en impasse calme à environ 15 minutes à pied du centre-ville. Vue dégagée et exposition plein soleil idéale pour une maison bioclimatique. Le permis de construire pour une maison individuelle d'environ 110 m² habitables est déjà purgé.",
  "Ce terrain clé en main, avec permis obtenu et purgé, permet de démarrer le chantier rapidement sans les délais d'instruction administrative habituels. La Roche-sur-Foron est une ville dynamique du Faucigny, à 25 km de Genève et 35 km d'Annecy.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut prendre la suite du dossier permis ou soumettre un nouveau projet selon vos souhaits.",
 ],
 points: [
  "660 m² — permis purgé — La Roche-sur-Foron (74800)",
  "Vue dégagée — exposition plein soleil",
  "Maison ~110 m² habitables autorisée",
  "Impasse calme — 15 min à pied centre-ville",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "La Roche-sur-Foron (74800) est la sous-préfecture du Faucigny, bien équipée en commerces, services et établissements scolaires. Le permis de construire purgé réduit significativement le délai avant démarrage des travaux. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-la-roche-sur-foron-755m2-hauteurs",
 commune: "La Roche-sur-Foron",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 755,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 161000,
 statut: "Disponible",
 image: "/images/terrains/la-roche-sur-foron-755.jpg",
 images: ["/images/terrains/la-roche-sur-foron-755.jpg"],
 accroche: "755 m² — Hauteurs de La Roche-sur-Foron — Prix accessible (74800)",
 description: [
  "Terrain à bâtir de 755 m² sur les hauteurs de La Roche-sur-Foron (74800), à 10 minutes en voiture du centre-ville. Secteur calme et dégagé, en zone Ud2 avec un CES de 0,20 permettant environ 150 m² d'emprise au sol.",
  "Un prix attractif pour une parcelle bien dimensionnée dans une commune équipée. Opportunité intéressante pour un premier projet de construction ou une maison familiale avec jardin généreux.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut analyser les règles du PLU et simuler votre projet sur cette parcelle.",
 ],
 points: [
  "755 m² — zone Ud2, CES 0,20 — La Roche-sur-Foron (74800)",
  "Emprise au sol possible : ~150 m²",
  "10 min voiture du centre-ville",
  "Prix accessible — secteur en hauteur",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Les hauteurs de La Roche-sur-Foron offrent généralement une vue dégagée sur la vallée de l'Arve. La zone Ud2 est typiquement un secteur résidentiel de densité modérée, bien adapté aux maisons individuelles avec jardin. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Contamine-sur-Arve (74130) ─────────────────────────────────────────────

 {
 slug: "terrain-contamine-sur-arve-647m2-residentiel",
 commune: "Contamine-sur-Arve",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 647,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 243000,
 statut: "Disponible",
 image: "/images/terrains/contamine-sur-arve-647.jpg",
 images: ["/images/terrains/contamine-sur-arve-647.jpg"],
 accroche: "647 m² viabilisé — 3 min A40 — Contamine-sur-Arve (74130)",
 description: [
  "Terrain à bâtir de 647 m² entièrement viabilisé dans un secteur résidentiel ensoleillé de Contamine-sur-Arve (74130), à 3 minutes de l'échangeur A40 de Findrol et à proximité du Centre Hospitalier Alpes-Léman (CHAL).",
  "La zone constructible (CES 0,25) permet une emprise au sol d'environ 162 m², idéale pour une maison individuelle de 130 à 150 m² habitables. Toutes les viabilités sont raccordées en limite de parcelle.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION accompagne votre projet depuis l'étude de faisabilité jusqu'à la réception du chantier.",
 ],
 points: [
  "647 m² viabilisé — Contamine-sur-Arve (74130)",
  "Emprise ~162 m² (CES 0,25)",
  "3 min A40 (échangeur Findrol)",
  "Proximité CHAL — secteur résidentiel ensoleillé",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Contamine-sur-Arve (74130) est une commune du Faucigny en développement, très bien desservie par l'A40 Genève–Chamonix. La proximité du CHAL en fait un secteur attractif pour les familles. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-contamine-sur-arve-445m2-plein-sud",
 commune: "Contamine-sur-Arve",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 445,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 137000,
 statut: "Disponible",
 image: "/images/terrains/contamine-sur-arve-445.jpg",
 images: ["/images/terrains/contamine-sur-arve-445.jpg"],
 accroche: "445 m² plein sud — Vue dégagée — Hauteurs de Contamine-sur-Arve (74130)",
 description: [
  "Terrain à bâtir de 445 m² en exposition plein sud sur les hauteurs de Contamine-sur-Arve (74130). Vue dégagée sur les reliefs environnants, idéale pour tirer parti du rayonnement solaire en conception bioclimatique.",
  "Malgré une surface modeste, la configuration de la parcelle et son orientation permettent de concevoir une maison individuelle compacte et performante, d'environ 90 à 110 m² de surface de plancher.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut réaliser une étude de faisabilité solaire et thermique sur cette parcelle.",
 ],
 points: [
  "445 m² — exposition plein sud — vue dégagée",
  "Hauteurs de Contamine-sur-Arve (74130)",
  "Prix accessible — bon potentiel bioclimatique",
  "Maison compacte ~90–110 m² envisageable",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "L'exposition plein sud de ce terrain de Contamine-sur-Arve (74130) est un atout majeur en zone alpine, où les gains solaires passifs représentent jusqu'à 30 % des besoins de chauffage. La surface modérée permet de maîtriser le budget de construction global. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Viuz-en-Sallaz (74250) ─────────────────────────────────────────────────

 {
 slug: "terrain-viuz-en-sallaz-500m2-plat",
 commune: "Viuz-en-Sallaz",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 500,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 180000,
 statut: "Disponible",
 image: "/images/terrains/viuz-en-sallaz-500.jpg",
 images: ["/images/terrains/viuz-en-sallaz-500.jpg"],
 accroche: "500 m² plat clôturé — Exposition Sud/Ouest — Viuz-en-Sallaz (74250)",
 description: [
  "Terrain à bâtir de 500 m² parfaitement plat et clôturé à Viuz-en-Sallaz (74250), avec accès goudronné et exposition Sud/Ouest favorable. Secteur calme et résidentiel, proche des commodités de la commune et bien desservi vers Annemasse et Genève.",
  "Une étude de maison individuelle d'environ 110 m² habitables a déjà été réalisée sur cette parcelle. Le terrain plat simplifie les fondations et réduit le coût global du projet, notamment en zone sismique 3.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut s'appuyer sur les études existantes ou proposer un projet sur mesure.",
 ],
 points: [
  "500 m² plat et clôturé — accès goudronné",
  "Exposition Sud/Ouest — Viuz-en-Sallaz (74250)",
  "Plans de maison ~110 m² déjà étudiés",
  "Fondations simplifiées grâce au terrain plat",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Viuz-en-Sallaz (74250) est une commune du Faucigny à 20 minutes d'Annemasse. Un terrain plat en zone sismique 3 représente un avantage concret : les fondations sont moins complexes et moins coûteuses qu'en forte pente. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-viuz-en-sallaz-1423m2-vue-degagee",
 commune: "Viuz-en-Sallaz",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 1423,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 220000,
 statut: "Disponible",
 image: "/images/terrains/viuz-en-sallaz-1423.jpg",
 images: ["/images/terrains/viuz-en-sallaz-1423.jpg"],
 accroche: "1 423 m² vue dégagée — Situation dominante — Viuz-en-Sallaz (74250)",
 description: [
  "Grand terrain de 1 423 m² en situation dominante à Viuz-en-Sallaz (74250), offrant une vue dégagée sur le paysage environnant. Une surface rare permettant d'envisager un projet ambitieux avec vastes espaces extérieurs.",
  "Viuz-en-Sallaz, au cœur du Faucigny, est à 20 minutes d'Annemasse et bien desservie vers Bonneville et La Roche-sur-Foron. La commune est appréciée pour son cadre rural préservé et ses équipements de proximité.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION réalise une simulation d'emprise complète selon les règles du PLU local.",
 ],
 points: [
  "1 423 m² — vue dégagée — situation dominante",
  "Viuz-en-Sallaz (74250) — Faucigny",
  "20 min Annemasse, proche Bonneville",
  "Grand terrain — espaces extérieurs généreux",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Un terrain de plus de 1 400 m² en situation dominante est une ressource rare dans le Faucigny. Cette parcelle de Viuz-en-Sallaz (74250) convient aussi bien à une maison de plain-pied avec jardin qu'à un projet avec piscine et dépendances. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 // ── Saint-Jean-de-Tholome (74250) ──────────────────────────────────────────

 {
 slug: "terrain-saint-jean-de-tholome-838m2-pied-du-mole",
 commune: "Saint-Jean-de-Tholome",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 838,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 230000,
 statut: "Disponible",
 image: "/images/terrains/saint-jean-de-tholome-838.jpg",
 images: ["/images/terrains/saint-jean-de-tholome-838.jpg"],
 accroche: "838 m² viabilisé — Au pied du Môle — Saint-Jean-de-Tholome (74250)",
 description: [
  "Terrain à bâtir de 838 m² entièrement plat et viabilisé à Saint-Jean-de-Tholome (74250), au pied du massif du Môle. Ensoleillement maximal grâce à la situation dégagée. À 30 minutes de Genève et 40 minutes d'Annecy, commune calme appréciée des frontaliers.",
  "Deux lots sont disponibles sur ce secteur (838 m² et 853 m²), permettant à des proches de s'installer côte à côte. Toutes les viabilités sont raccordées, pour un démarrage de chantier rapide après l'obtention du permis.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut gérer votre projet de A à Z depuis la conception jusqu'à la livraison.",
 ],
 points: [
  "838 m² plat et viabilisé — Saint-Jean-de-Tholome (74250)",
  "Au pied du Môle — ensoleillement maximal",
  "30 min Genève, 40 min Annecy",
  "Second lot de 853 m² disponible à proximité",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Saint-Jean-de-Tholome (74250) est une commune paisible du Faucigny, nichée entre le Môle et la vallée du Giffre. Elle attire les familles en quête de cadre naturel préservé sans s'éloigner du bassin d'emploi genevois. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-saint-jean-de-tholome-347m2-plein-sud",
 commune: "Saint-Jean-de-Tholome",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 347,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 162000,
 statut: "Disponible",
 image: "/images/terrains/saint-jean-de-tholome-347.jpg",
 images: ["/images/terrains/saint-jean-de-tholome-347.jpg"],
 accroche: "347 m² plein sud — Vue montagne — Saint-Jean-de-Tholome (74250)",
 description: [
  "Terrain à bâtir de 347 m² en exposition plein sud avec vue sur les montagnes environnantes à Saint-Jean-de-Tholome (74250). Parcelle entièrement viabilisée (eau, électricité, télécoms), prête à construire.",
  "Surface compacte idéale pour une maison individuelle de 80 à 100 m² habitables. L'orientation plein sud maximise les apports solaires passifs, un avantage concret pour atteindre les objectifs de la RE2020 sans surcoût.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION réalise une étude de faisabilité complète adaptée à cette surface.",
 ],
 points: [
  "347 m² — plein sud — vue montagne",
  "Saint-Jean-de-Tholome (74250)",
  "Entièrement viabilisé — prêt à construire",
  "Maison compacte 80–100 m² optimale",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "L'exposition plein sud de ce terrain de Saint-Jean-de-Tholome (74250) compense la surface modérée par un potentiel bioclimatique élevé. Une maison bien conçue sur cette parcelle peut atteindre un Bbio inférieur à 50 grâce aux apports solaires directs. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 {
 slug: "terrain-saint-jean-de-tholome-543m2-residentiel",
 commune: "Saint-Jean-de-Tholome",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 543,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 187000,
 statut: "Disponible",
 image: "/images/terrains/saint-jean-de-tholome-543.jpg",
 images: ["/images/terrains/saint-jean-de-tholome-543.jpg"],
 accroche: "543 m² tout viabilisé — Secteur résidentiel calme — Saint-Jean-de-Tholome (74250)",
 description: [
  "Terrain à bâtir de 543 m² entièrement viabilisé à Saint-Jean-de-Tholome (74250) dans un secteur résidentiel calme. Raccordements eau, électricité, télécoms et tout-à-l'égout réalisés en bordure de parcelle.",
  "En zone constructible (CES 0,30), la surface plancher autorisée avoisine 200 m², permettant une maison individuelle généreuse avec de beaux espaces intérieurs. Saint-Jean-de-Tholome est à 30 minutes de Genève et 40 minutes d'Annecy.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION accompagne chaque étape depuis la conception jusqu'à la réception.",
 ],
 points: [
  "543 m² — tout-à-l'égout et toutes viabilités",
  "Saint-Jean-de-Tholome (74250) — secteur calme",
  "CES 0,30 — surface plancher ~200 m² possible",
  "30 min Genève, 40 min Annecy",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Saint-Jean-de-Tholome (74250) offre un cadre de vie préservé entre le Môle et les Préalpes du Chablais. Un terrain de 543 m² avec tout-à-l'égout en bordure est une configuration favorable qui limite les coûts imprévus de raccordement. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Bonneville (74130) ─────────────────────────────────────────────────────

 {
 slug: "terrain-bonneville-395m2-permis-purge",
 commune: "Bonneville",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 395,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 147000,
 statut: "Disponible",
 image: "/images/terrains/bonneville-395.jpg",
 images: ["/images/terrains/bonneville-395.jpg"],
 accroche: "395 m² centre-ville — Permis purgé — Bonneville (74130)",
 description: [
  "Terrain à bâtir de 395 m² en plein centre-ville de Bonneville (74130) avec permis de construire déjà purgé pour une maison individuelle d'environ 100 m² habitables, 3 à 4 chambres et garage double. Tous les commerces, services et établissements scolaires sont accessibles à pied.",
  "Le permis purgé représente un avantage considérable : pas de délai d'instruction, pas d'incertitude réglementaire. Le chantier peut démarrer dès l'acquisition sans attendre les 6 à 12 mois habituels pour obtenir et purger un permis de construire.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut s'appuyer sur le dossier existant ou adapter le projet selon vos besoins.",
 ],
 points: [
  "395 m² — permis purgé — centre-ville Bonneville (74130)",
  "Maison ~100 m², 3-4 chambres, garage double autorisés",
  "Tous commerces et services à pied",
  "Chantier démarrable immédiatement après acquisition",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Bonneville (74130) est la sous-préfecture de la Haute-Savoie, chef-lieu du Faucigny, bien desservie par l'A40 à 30 km de Genève. Un permis purgé en centre-ville est une ressource rare qui justifie pleinement le budget. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 // ── Saint-Pierre-en-Faucigny (74800) ───────────────────────────────────────

 {
 slug: "terrain-saint-pierre-en-faucigny-850m2-zone-uc",
 commune: "Saint-Pierre-en-Faucigny",
 departement: "Haute-Savoie (74)",
 zone: "Faucigny",
 type: "Terrain à bâtir",
 surfaceTerrain: 850,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 250000,
 statut: "Disponible",
 image: "/images/terrains/saint-pierre-en-faucigny-850.jpg",
 images: ["/images/terrains/saint-pierre-en-faucigny-850.jpg"],
 accroche: "850 m² zone UC — Issu de division — Saint-Pierre-en-Faucigny (74800)",
 description: [
  "Terrain à bâtir de 850 m² à Saint-Pierre-en-Faucigny (74800), issu d'une division parcellaire d'un ancien terrain de sport. En zone UC avec un CES de 30 %, l'emprise au sol autorisée atteint 255 m², une capacité constructive très confortable. Les viabilités sont disponibles en bordure de parcelle.",
  "Saint-Pierre-en-Faucigny est une commune active du Faucigny, à 5 km de La Roche-sur-Foron et bien desservie par les axes vers Genève et Annecy. La vue dégagée sur les reliefs est un atout apprécié dans ce secteur.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION analyse votre projet selon les règles de la zone UC et optimise l'emprise au sol.",
 ],
 points: [
  "850 m² — zone UC, CES 30 % — emprise ~255 m²",
  "Saint-Pierre-en-Faucigny (74800)",
  "Issu de division — viabilités en bordure",
  "Vue dégagée sur les reliefs",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "La zone UC de Saint-Pierre-en-Faucigny (74800) autorise une densité constructive généreuse pour une commune de taille intermédiaire du Faucigny. Un CES de 30 % sur 850 m² ouvre la porte à une maison individuelle avec grande surface de plain-pied. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },

 // ── Glières-Val-de-Borne (74130) ───────────────────────────────────────────

 {
 slug: "terrain-glieres-val-de-borne-1530m2-montagne",
 commune: "Glières-Val-de-Borne",
 departement: "Haute-Savoie (74)",
 zone: "Préalpes savoisiennes",
 type: "Terrain à bâtir",
 surfaceTerrain: 1530,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 189000,
 statut: "Disponible",
 image: "/images/terrains/glieres-val-de-borne-1530.jpg",
 images: ["/images/terrains/glieres-val-de-borne-1530.jpg"],
 accroche: "1 530 m² plein sud — Vue montagne — Permis chalet purgé — Glières-Val-de-Borne (74130)",
 description: [
  "Terrain à bâtir de 1 530 m² en exposition plein sud avec vue dégagée sur le massif des Aravis à Glières-Val-de-Borne (74130), en zone UHI. Un permis de construire pour un chalet de 138 m² habitables est déjà purgé et utilisable — ou peut être remplacé par un nouveau projet selon vos souhaits.",
  "Situation stratégique à 45 minutes de Genève, 45 minutes d'Annecy et 10 minutes des premières stations de ski du secteur. Ce grand terrain à prix accessible représente une opportunité rare pour un projet de résidence principale ou de chalet en montagne.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION est spécialisé dans la construction de maisons et chalets ossature bois adaptés aux contraintes alpines.",
 ],
 points: [
  "1 530 m² — plein sud — vue Aravis — Glières-Val-de-Borne (74130)",
  "Zone UHI — permis chalet 138 m² déjà purgé",
  "45 min Genève et Annecy — 10 min stations de ski",
  "Prix accessible pour une surface exceptionnelle",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Glières-Val-de-Borne (74130) est une commune des Préalpes savoisiennes, réputée pour son plateau naturel et son ensoleillement. La zone UHI (Urbaine à vocation d'Habitat Isolé) est adaptée aux constructions de type chalet. La RE2020 et les matériaux biosourcés y sont particulièrement pertinents. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
  { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
 ],
 },

 // ── Fillinges (74250) ──────────────────────────────────────────────────────

 {
 slug: "terrain-fillinges-491m2-secteur-mijouet",
 commune: "Fillinges",
 departement: "Haute-Savoie (74)",
 zone: "Genevois français",
 type: "Terrain à bâtir",
 surfaceTerrain: 491,
 surfaceHabitable: 0,
 pieces: 0,
 budget: 179000,
 statut: "Disponible",
 image: "/images/terrains/fillinges-491.jpg",
 images: ["/images/terrains/fillinges-491.jpg"],
 accroche: "491 m² vue montagnes — Libre constructeur — Fillinges (74250)",
 description: [
  "Terrain à bâtir de 491 m² en secteur résidentiel calme de Fillinges (74250), avec vue sur les montagnes environnantes. Exposition Sud-Est favorable. Libre de tout constructeur. Zone UC avec un CES de 0,18 permettant environ 88 m² d'emprise au sol.",
  "Fillinges est une commune du Genevois français à 15 minutes d'Annemasse, appréciée pour son cadre de vie tranquille tout en restant à distance raisonnable des axes transfrontaliers vers Genève.",
  "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut optimiser l'implantation de votre maison pour tirer le meilleur parti de l'exposition et de la vue.",
 ],
 points: [
  "491 m² — exposition Sud-Est — vue montagnes",
  "Fillinges (74250) — 15 min Annemasse",
  "Libre de tout constructeur",
  "Zone UC, CES 0,18 — emprise ~88 m²",
  "Terrain sous réserve de disponibilité — partenaire foncier",
 ],
 contexte: "Fillinges (74250) est une commune résidentielle du Genevois français bien desservie, entre Annemasse et Taninges. La vue sur les montagnes depuis le secteur Mijouet est un atout paysager rare à ce niveau de prix pour le secteur. Zone sismique 3.",
 guidesLies: [
  { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
 ],
 },
];

export function getAnnonce(slug: string): Annonce | undefined {
 return annonces.find((a) => a.slug === slug);
}

export function getAutresAnnonces(slug: string): Annonce[] {
 const current = annonces.find((a) => a.slug === slug);
 const others = annonces.filter((a) => a.slug !== slug);
 if (!current) return others.slice(0, 3);
 const sameZoneAndType = others.filter((a) => a.zone === current.zone && a.type === current.type);
 const sameZone = others.filter((a) => a.zone === current.zone && a.type !== current.type);
 const rest = others.filter((a) => a.zone !== current.zone);
 return [...sameZoneAndType, ...sameZone, ...rest].slice(0, 3);
}
