export type Statut = "Disponible" | "En cours" | "Livré";

export interface GuideLie {
  titre: string;
  href: string;
}

export interface Annonce {
  slug: string;
  commune: string;
  departement: string;
  type: string;
  surfaceTerrain: number;
  surfaceHabitable: number;
  pieces: number;
  budget: number;
  statut: Statut;
  image: string;
  images: string[];
  accroche: string;
  description: string[];
  points: string[];
  zone: string;
  contexte: string;
  guidesLies: GuideLie[];
}

export const annonces: Annonce[] = [
  // --- Terrains issus du portefeuille partenaires fonciers ---
  {
    slug: "terrain-vulbens-407m2-clos-alizees",
    commune: "Vulbens",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 407,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 222600,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-maison-bois-montagne-1.jpg"],
    accroche: "407 m² viabilisé — Libre constructeur — Commerces, gare et TPG à pied — Frontière suisse",
    description: [
      "Lot à bâtir de 407 m² au sein d'un lotissement de 7 parcelles entièrement viabilisées à Vulbens (74520), à deux pas de la frontière suisse. Libre constructeur — aucune enseigne imposée. L'emprise constructible maximale est de 184 m² au sol.",
      "Toutes les viabilités sont raccordées directement sur le terrain. Les commerces, les écoles, la gare et les bus TPG reliant Genève sont accessibles à pied depuis la parcelle — un atout rare dans le Genevois français.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner votre projet depuis l'étude de faisabilité jusqu'à la réception du chantier.",
    ],
    points: [
      "407 m² dans un lotissement de 7 lots viabilisés",
      "Emprise constructible : 184 m² au sol",
      "Libre constructeur — toutes viabilités sur place",
      "Commerces, gare et bus TPG accessibles à pied",
      "À deux pas de la frontière suisse",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Vulbens est une commune du Genevois français (74520) très appréciée des frontaliers pour sa proximité immédiate avec la Suisse et la qualité de son cadre de vie. L'accès aux transports en commun transfrontaliers depuis le village est un avantage déterminant. La zone sismique 3 s'applique — bureau d'études structure systématiquement intégré par M&M CONSTRUCTION.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
    ],
  },
  {
    slug: "terrain-vulbens-588m2-clos-alizees",
    commune: "Vulbens",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 588,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 265300,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-1.jpg",
    images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "588 m² viabilisé — Libre constructeur — Transports à pied — Proche frontière suisse",
    description: [
      "Lot de 588 m² au sein du même lotissement de 7 parcelles à Vulbens (74520), entièrement viabilisé, libre constructeur. Une surface plus généreuse pour envisager un projet de maison familiale avec de beaux espaces extérieurs.",
      "Toutes les viabilités sont présentes sur le terrain. La situation du lotissement, à distance de marche de la gare, des commerces et des bus TPG, offre un confort de vie rare dans ce secteur très recherché du Genevois français.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "588 m² dans un lotissement de 7 lots viabilisés",
      "Libre constructeur — aucune contrainte d'enseigne",
      "Toutes viabilités sur place",
      "Commerces, gare et bus TPG à pied",
      "Frontière suisse à deux pas",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Même lotissement que la parcelle de 407 m² à Vulbens (74520). La surface supérieure de ce lot permet d'envisager une villa avec jardin et terrasse de belle ampleur. Le secteur est classé en zone sismique 3 — bureau d'études structure requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-feigeres-1394m2-projet-demolition",
    commune: "Feigères",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 1394,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 259000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "1 394 m² en zone UB — Boisé avec ruisseau — Libre constructeur — Portes de Genève",
    description: [
      "Grande parcelle de 1 394 m² à Feigères (74160), aux portes de Genève, classée en zone UB. Le terrain boisé, en légère pente, traversé par un ruisseau, offre un cadre naturel préservé et rare dans ce secteur.",
      "La parcelle accueille actuellement une maison à démolir ainsi qu'une annexe. Un budget de démolition, de désamiantage éventuel et d'élagage est à intégrer dans l'enveloppe globale du projet — à évaluer précisément lors de l'étude de faisabilité. Le projet permettra la construction d'une maison individuelle, sous réserve des règles du PLU local.",
      "Libre constructeur. Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner l'ensemble du projet, de l'analyse réglementaire à la réception du chantier.",
    ],
    points: [
      "1 394 m² en zone UB — construction d'une maison individuelle possible",
      "Terrain boisé en pente avec ruisseau — cadre naturel préservé",
      "Démolition de l'existant et désamiantage à prévoir (à chiffrer)",
      "Libre constructeur — aucune enseigne imposée",
      "Feigères (74160) — aux portes de Genève",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Feigères est une commune du Genevois français (74160) très appréciée pour son environnement calme et sa proximité avec Genève et Saint-Julien-en-Genevois. Ce type de grande parcelle boisée, avec bâtisse existante à démolir, constitue une opportunité de créer un projet sur-mesure dans un cadre naturel. Les coûts de démolition et d'éventuels travaux préalables sont à évaluer par des professionnels avant engagement. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
    ],
  },
  {
    slug: "terrain-beaumont-573m2-hameau-travers",
    commune: "Beaumont",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 573,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 350000,
    statut: "Disponible",
    image: "/images/hero-extension-bois-golden.jpg",
    images: ["/images/hero-extension-bois-golden.jpg", "/images/hero-maison-bois-montagne-1.jpg"],
    accroche: "573 m² — Vue dominante sur Genève — Hameau des Travers — Sentiers du Salève",
    description: [
      "Terrain de 573 m² dans le hameau des Travers à Beaumont (74160), bénéficiant d'une vue dominante sur Genève et le bassin genevois. La frontière suisse n'est qu'à quelques minutes, et les sentiers de randonnée du Salève sont accessibles depuis la parcelle.",
      "Un emplacement d'exception pour construire une villa en ossature bois tirant pleinement parti du panorama. La topographie du site et son exposition sont à analyser lors de l'étude de faisabilité afin d'optimiser l'orientation architecturale.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "573 m² dans le hameau des Travers à Beaumont",
      "Vue dominante sur Genève et le bassin genevois",
      "Quelques minutes de la frontière suisse",
      "Sentiers du Salève accessibles depuis la parcelle",
      "Etude de faisabilité M&M CONSTRUCTION sur demande",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Beaumont (74160) est une commune du Genevois français à mi-hauteur, connue pour ses vues panoramiques sur Genève. Le hameau des Travers est un secteur calme et résidentiel très recherché des frontaliers. Zone sismique 3 — bureau d'études structure intégré systématiquement.",
    guidesLies: [
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-presilly-661m2-viabilise",
    commune: "Présilly",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 661,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 370000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-1.jpg",
    images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "661 m² viabilisé — Secteur rare du Genevois français — Présilly (74160)",
    description: [
      "Terrain à bâtir de 661 m² entièrement viabilisé à Présilly (74160), dans le Genevois français. Les opportunités foncières constructibles sont rares dans ce secteur prisé par les frontaliers pour sa qualité de vie et sa position stratégique à proximité de la Suisse.",
      "La viabilisation complète du terrain simplifie les démarches et réduit les délais : les raccordements sont déjà en place, le permis de construire peut être déposé rapidement.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner votre projet de construction.",
    ],
    points: [
      "661 m² entièrement viabilisé",
      "Présilly (74160) — secteur rare du Genevois français",
      "Raccordements en place — dépôt de PC immédiatement possible",
      "Cadre calme et verdoyant à proximité de la Suisse",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Présilly est une commune du Genevois français (74160) à faible pression urbaine, ce qui rend les terrains constructibles particulièrement rares et recherchés. Proximité de Saint-Julien-en-Genevois et de la frontière suisse. Zone sismique 3.",
    guidesLies: [
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-neydens-770m2-viabilise",
    commune: "Neydens",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 770,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 360000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-maison-bois-montagne-2.jpg"],
    accroche: "770 m² viabilisé — Vue montagnes — Frontière suisse à proximité — Neydens (74160)",
    description: [
      "Terrain à bâtir de 770 m² entièrement viabilisé à Neydens (74160), à proximité immédiate de la frontière suisse et bénéficiant d'une belle vue sur les montagnes environnantes. Les commerces sont accessibles rapidement depuis la parcelle.",
      "Neydens est l'une des communes les plus recherchées du Genevois français pour sa situation exceptionnelle entre Genève, Annecy et le massif du Salève. Un terrain rare dans ce secteur à haute demande foncière.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "770 m² entièrement viabilisé",
      "Vue sur les montagnes",
      "Frontière suisse à proximité immédiate",
      "Commerces accessibles rapidement",
      "Neydens (74160) — secteur très recherché",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Neydens (74160) est une commune particulièrement prisée du Genevois français, à la croisée des routes vers Genève, Annecy et le Salève. Le foncier y est sous forte tension et les terrains viabilisés à plus de 700 m² sont devenus très rares. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-saint-julien-378m2-cervonnex-plein-sud",
    commune: "Saint-Julien-en-Genevois",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 378,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 320000,
    statut: "Disponible",
    image: "/images/hero-extension-bois-golden.jpg",
    images: ["/images/hero-extension-bois-golden.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "378 m² plat plein sud — Cervonnex — École et commerces à 5 min — Accès Suisse immédiat",
    description: [
      "Terrain plat de 378 m², exposé plein sud, dans le hameau de Cervonnex, quartier de Saint-Julien-en-Genevois (74160). L'accès à la Suisse est quasi immédiat depuis ce secteur, idéal pour les frontaliers travaillant à Genève.",
      "L'exposition plein sud maximise les apports solaires passifs et le confort thermique de la future construction. École et commerces sont accessibles en 5 minutes. Un emplacement central dans le Genevois français.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "378 m² plat — exposition plein sud",
      "Hameau de Cervonnex — Saint-Julien-en-Genevois",
      "Accès à la Suisse quasi immédiat",
      "École et commerces à 5 minutes",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Saint-Julien-en-Genevois (74160) est la principale commune du Genevois français côté France, à 15 km de Genève. Le hameau de Cervonnex bénéficie d'une situation privilégiée avec un accès rapide à la frontière et un environnement résidentiel calme. Zone sismique 3 — bureau d'études structure systématiquement requis.",
    guidesLies: [
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-annemasse-740m2-pc-accepte",
    commune: "Annemasse",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 740,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 290000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "740 m² plat arboré — PC accepté maison 135 m² + garage — Impasse calme — Tram à proximité",
    description: [
      "Terrain plat et arboré de 740 m², sans vis-à-vis, situé dans une impasse calme à Annemasse (74100), aux portes de Genève. Un permis de construire pour une maison de 135 m² avec garage a déjà été déposé et accepté sur cette parcelle — un gain de temps appréciable.",
      "La parcelle bénéficie de la proximité des transports en commun du réseau Grand Genève et sera desservie par le futur tramway. Environnement verdoyant et préservé, rare en secteur annemassien.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "740 m² plat et arboré — sans vis-à-vis",
      "PC accepté pour maison 135 m² + garage",
      "Impasse calme — aucune nuisance de transit",
      "Transports en commun et futur tram à proximité",
      "Annemasse (74100) — portes de Genève",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Ce terrain à Annemasse présente un avantage rare : un permis de construire déjà accepté, qui réduit significativement le délai avant démarrage du chantier. La situation dans une impasse garantit la tranquillité et l'absence de circulation de transit. Zone sismique 3 — bureau d'études structure intégré.",
    guidesLies: [
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-cranves-sales-715m2-lossy-viabilise",
    commune: "Cranves-Sales",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 715,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 319500,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "715 m² viabilisé — Vue dégagée — Hameau de Lossy — Cranves-Sales (74380)",
    description: [
      "Terrain à bâtir de 715 m² entièrement viabilisé dans le charmant hameau de Lossy à Cranves-Sales (74380). La parcelle bénéficie d'une belle vue dégagée sur les environs, avec toutes les viabilités raccordées directement sur le terrain.",
      "L'emprise constructible maximale autorisée est de 225 m² au sol — de quoi concevoir une maison familiale de belle ampleur avec des espaces extérieurs généreux. Cranves-Sales est une commune résidentielle prisée du Genevois français, à 10 minutes d'Annemasse et 20 minutes de Genève.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "715 m² entièrement viabilisé — vue dégagée",
      "Hameau de Lossy à Cranves-Sales",
      "Emprise constructible : 225 m² au sol",
      "Toutes viabilités raccordées sur la parcelle",
      "10 min Annemasse — 20 min Genève",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Le hameau de Lossy à Cranves-Sales (74380) est un secteur résidentiel calme, bien positionné dans le Genevois français. La commune est sous forte pression foncière due à la demande des frontaliers. Les terrains viabilisés avec vue sont particulièrement recherchés. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-cranves-sales-720m2-chemin-moulins",
    commune: "Cranves-Sales",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 720,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 249000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "720 m² en zone UHp — Exposé Sud/Sud-Ouest — Libre constructeur — Proche Annemasse",
    description: [
      "Parcelle de 720 m² au Chemin des Moulins à Cranves-Sales (74380), classée en zone UHp, légèrement en pente et exposée Sud/Sud-Ouest pour un ensoleillement naturel optimal. L'emprise constructible est de 144 m², permettant une maison R+1 avec combles aménageables.",
      "Libre constructeur — pleine liberté de conception. Proche d'Annemasse et des axes autoroutiers desservant Genève. Les terrains constructibles sont rares dans ce secteur très recherché du Genevois français.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "720 m² en zone UHp — légèrement en pente",
      "Exposition Sud/Sud-Ouest — ensoleillement optimal",
      "Emprise constructible : 144 m² — R+1 avec combles possible",
      "Libre constructeur",
      "Proche Annemasse et axes autoroutiers vers Genève",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Cranves-Sales (74380) est une commune résidentielle du Genevois français avec un accès rapide à Annemasse et à la frontière suisse. Le secteur du Chemin des Moulins bénéficie d'un environnement calme. Les terrains constructibles y sont rares et très demandés. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-cranves-sales-615m2-lossy-reseaux-proximite",
    commune: "Cranves-Sales",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 615,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 298000,
    statut: "Disponible",
    image: "/images/hero-extension-bois-jardin.jpg",
    images: ["/images/hero-extension-bois-jardin.jpg", "/images/hero-maison-bois-montagne-2.jpg"],
    accroche: "615 m² — Vue Voirons et Salève — Transports 3 min — Gare Annemasse 6 min",
    description: [
      "Terrain de 615 m² dans le hameau de Lossy à Cranves-Sales (74380), offrant une belle vue sur les Voirons et le Salève. Non viabilisé, les réseaux sont disponibles à proximité immédiate de la parcelle — le raccordement est à prévoir dans le budget.",
      "Le terrain accueille une petite construction existante. Les transports en commun avec parking relais sont à 3 minutes, la gare d'Annemasse à 6 minutes en voiture, et l'ensemble des commodités de l'agglomération annemassienne est accessible rapidement.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "615 m² avec vue sur les Voirons et le Salève",
      "Hameau de Lossy — cadre calme et verdoyant",
      "Réseaux à proximité immédiate (viabilisation à prévoir)",
      "Transports en commun avec PR à 3 minutes",
      "Gare d'Annemasse à 6 minutes en voiture",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Ce terrain de Cranves-Sales (74380) présente la particularité de ne pas être encore viabilisé, ce qui justifie un prix inférieur aux parcelles équivalentes raccordées. Les réseaux étant à proximité immédiate, le coût de raccordement reste limité. À intégrer dans le budget global avec une estimation précise lors de l'étude de faisabilité. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
    ],
  },
  {
    slug: "terrain-neydens-782m2-la-forge",
    commune: "Neydens",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 782,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 360000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-maison-bois-montagne-1.jpg"],
    accroche: "782 m² plein sud/ouest — Lotissement La Forge — Entièrement viabilisé — Neydens (74160)",
    description: [
      "Terrain de 782 m² au sein d'un lotissement de 4 parcelles à Neydens (74160), secteur La Forge. Exposition idéale plein sud et plein ouest, garantissant un ensoleillement optimal tout au long de la journée.",
      "Entièrement viabilisé et raccordé à tous les réseaux (électricité, eau potable, eaux usées, eaux pluviales). La configuration de la parcelle permet d'envisager la construction d'une ou deux habitations individuelles ou mitoyennes, avec de généreux espaces extérieurs.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "782 m² dans le lotissement La Forge à Neydens",
      "Exposition plein sud et ouest — ensoleillement optimal",
      "Entièrement viabilisé — tous réseaux raccordés",
      "1 ou 2 habitations envisageables selon le PLU",
      "Neydens (74160) — Genevois français",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Le lotissement La Forge à Neydens (74160) est un projet de 4 lots bien exposés dans une commune très recherchée du Genevois français. La viabilisation complète et l'exposition plein sud/ouest constituent deux atouts majeurs pour la qualité de vie future. Zone sismique 3 — bureau d'études structure requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-neydens-831m2-la-forge",
    commune: "Neydens",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 831,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 375000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-1.jpg",
    images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "831 m² plein sud/ouest — Lotissement La Forge — Viabilisé — Surface généreuse",
    description: [
      "Parcelle de 831 m² dans le même lotissement La Forge à Neydens (74160), offrant une surface encore plus généreuse pour concevoir un projet ambitieux. Exposition plein sud et ouest pour un ensoleillement optimal, entièrement viabilisée et raccordée à tous les réseaux.",
      "La configuration de cette grande parcelle permet d'envisager une villa spacieuse avec jardins paysagés et espaces extérieurs de qualité, tout en conservant la possibilité d'une habitation mitoyenne selon le projet.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "831 m² — surface généreuse pour un grand projet",
      "Lotissement La Forge à Neydens — 4 lots au total",
      "Exposition plein sud et ouest",
      "Entièrement viabilisé — tous réseaux raccordés",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Plus grande parcelle du lotissement La Forge à Neydens (74160). La surface de 831 m² permet d'envisager une villa avec jardin et terrasse de belle envergure. Même cadre d'exception que les autres lots du lotissement. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-vetraz-monthoux-462m2-viabilise",
    commune: "Vétraz-Monthoux",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 462,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 225000,
    statut: "Disponible",
    image: "/images/hero-extension-bois-golden.jpg",
    images: ["/images/hero-extension-bois-golden.jpg", "/images/hero-maison-bois-montagne-1.jpg"],
    accroche: "462 m² constructible — Portes de Genève — Résidentiel calme — Vétraz-Monthoux (74100)",
    description: [
      "Terrain constructible de 462 m² à Vétraz-Monthoux (74100), aux portes de Genève, dans un environnement résidentiel calme entre lac et montagnes. La viabilisation sera réalisée par l'acquéreur lors du dépôt du permis de construire.",
      "Vétraz-Monthoux est une commune recherchée pour la qualité de vie qu'elle offre à ses habitants : accès rapide à la Suisse et aux zones d'emploi genevoises, commerces, écoles et infrastructures sportives de proximité. Deux terrains constructibles sont disponibles sur ce secteur.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "462 m² constructible à Vétraz-Monthoux",
      "Viabilisation lors du dépôt du permis de construire",
      "Accès rapide à la Suisse et aux zones d'emploi genevoises",
      "Commerces, écoles, équipements sportifs à proximité",
      "Cadre résidentiel calme — entre lac et montagnes",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Vétraz-Monthoux (74100) fait partie de l'agglomération d'Annemasse, à moins de 15 minutes de Genève. La commune est appréciée pour son cadre résidentiel verdoyant et sa proximité avec la frontière suisse. Le fait que la viabilisation soit à la charge de l'acquéreur se reflète dans le prix de la parcelle. Zone sismique 3.",
    guidesLies: [
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-vetraz-monthoux-863m2-secteur-mairie",
    commune: "Vétraz-Monthoux",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 863,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 405000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "863 m² — Zone UH4 — CES 0,2 — 172 m² de plancher — Viabilisé — Secteur Mairie",
    description: [
      "Rare à la vente : terrain de 863 m² sur le côteau de Vétraz-Monthoux (74100), secteur Mairie, dans un cadre agréable et très recherché. Zone UH4, coefficient d'emprise au sol de 0,2 permettant une surface plancher de 172 m².",
      "Entièrement viabilisé et libre constructeur. L'exposition plein sud garantit un ensoleillement optimal — un avantage bioclimatique majeur pour optimiser les apports solaires passifs et réduire les besoins énergétiques futurs.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "863 m² — zone UH4 — CES 0,2",
      "Surface plancher autorisée : 172 m²",
      "Entièrement viabilisé — libre constructeur",
      "Exposition plein sud — apports solaires optimaux",
      "Secteur Mairie — Vétraz-Monthoux (74100)",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Ce terrain du secteur Mairie à Vétraz-Monthoux représente une opportunité rare par sa taille (863 m²) et sa situation dans l'une des zones résidentielles les plus prisées de la commune. La zone UH4 avec CES 0,2 permet une belle surface plancher tout en conservant de larges espaces extérieurs. Zone sismique 3 — bureau d'études structure intégré.",
    guidesLies: [
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-dingy-vuache-454m2-hameau-fleur-or",
    commune: "Dingy-en-Vuache",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 454,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 215000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "454 m² viabilisé — Le Hameau de la fleur d'Or — Libre constructeur — 30 min Genève",
    description: [
      "Terrain viabilisé de 454 m² dans le lotissement 'Le Hameau de la fleur d'Or' à Dingy-en-Vuache (74520), petite commune calme et sécurisée de Haute-Savoie. Raccordé aux réseaux d'eau potable, assainissement, électricité et télécom. Desservi par une voirie principale aménagée.",
      "Libre constructeur — pleine liberté de conception. À 20 minutes de Saint-Julien-en-Genevois et 30 minutes de Genève. Un cadre verdoyant et bucolique apprécié des travailleurs locaux et frontaliers amoureux de la nature.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "454 m² viabilisé dans le lotissement Le Hameau de la fleur d'Or",
      "Raccordé à tous les réseaux — voirie aménagée",
      "Libre constructeur",
      "20 min Saint-Julien-en-Genevois — 30 min Genève",
      "Cadre verdoyant et bucolique",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Dingy-en-Vuache (74520) est une petite commune de Haute-Savoie offrant un cadre de vie préservé, idéal pour les frontaliers souhaitant s'éloigner de l'agitation de l'agglomération annemassienne tout en restant à bonne distance de Genève. Zone sismique 3 — bureau d'études structure requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-presilly-681m2-vue-degagee",
    commune: "Présilly",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 681,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 390000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-1.jpg",
    images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "681 m² — Vue dégagée — Calme et verdoyant — Proche frontière suisse — Présilly (74160)",
    description: [
      "Beau terrain de 681 m² à Présilly (74160), dans un cadre calme et verdoyant, avec une vue dégagée sur les environs. Le lotissement sera desservi par un accès existant et raccordé aux réseaux existants — une mise en œuvre facilitée.",
      "À proximité de la frontière suisse, des axes de circulation et de l'ensemble des commodités du secteur genevois. Présilly est une commune très appréciée pour la qualité de vie qu'elle offre, à l'écart de l'agitation urbaine tout en restant proche de Genève.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "681 m² avec vue dégagée",
      "Cadre calme et verdoyant à Présilly (74160)",
      "Lotissement raccordé aux réseaux existants",
      "Proche de la frontière suisse et des axes de circulation",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Présilly (74160) est une commune rurale du Genevois français à faible pression urbaine, idéale pour les familles cherchant à construire dans un cadre naturel préservé tout en restant à proximité de Genève. Le foncier y est rare. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-viry-626m2-malagny",
    commune: "Viry",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 626,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 320000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "626 m² viabilisé — Secteur Malagny — Viry (74580) — Une seule habitation — Belle opportunité",
    description: [
      "Terrain de 626 m² issu d'une division parcellaire dans le secteur recherché de Malagny à Viry (74580). Les viabilités sont disponibles à proximité. La parcelle permet la construction d'une seule habitation individuelle — une configuration idéale pour un projet familial sur-mesure.",
      "Viry est une commune du Genevois français très appréciée pour son cadre résidentiel calme, à bonne distance de la frontière suisse. Le secteur de Malagny est particulièrement recherché. Une belle opportunité à saisir rapidement sur ce secteur.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "626 m² issu d'une division parcellaire",
      "Secteur Malagny — Viry (74580)",
      "Viabilités disponibles à proximité",
      "Construction d'une habitation individuelle",
      "Secteur très recherché du Genevois français",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Viry (74580) est une commune du Genevois français appréciée pour son environnement résidentiel calme. Le secteur de Malagny est l'un des plus recherchés de la commune. La division parcellaire récente garantit la constructibilité du terrain sous réserve de vérification du PLU. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
    ],
  },
  {
    slug: "terrain-archamps-466m2-ces-02",
    commune: "Archamps",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 466,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 270000,
    statut: "Disponible",
    image: "/images/hero-extension-bois-golden.jpg",
    images: ["/images/hero-extension-bois-golden.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "466 m² — 5 min frontière suisse — 20 min Genève — CES 0,2 — Libre constructeur",
    description: [
      "Terrain de 466 m² à Archamps (74160), sur les hauteurs, dans un quartier résidentiel calme. À seulement 5 minutes de la frontière suisse et 20 minutes du centre de Genève et de l'aéroport international — une localisation privilégiée pour les frontaliers.",
      "Libre constructeur, coefficient d'emprise au sol de 0,20. Les viabilités sont à prévoir, les réseaux étant disponibles à proximité de la parcelle. L'exposition du terrain et son implantation sur les hauteurs sont à valoriser dans la conception architecturale.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "466 m² — CES 0,2 — libre constructeur",
      "5 min frontière suisse — 20 min Genève et aéroport",
      "Sur les hauteurs d'Archamps — quartier résidentiel calme",
      "Viabilisation à prévoir (réseaux à proximité)",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Archamps (74160) est une commune stratégique du Genevois français, connue pour son technopôle et son accès direct à Genève en 10-20 minutes. Ce terrain sur les hauteurs offre une implantation calme avec les avantages de proximité d'Archamps. Zone sismique 3 — bureau d'études structure requis. M&M CONSTRUCTION intervient régulièrement sur la commune.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-archamps-822m2-hauteurs",
    commune: "Archamps",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 822,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 320000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-1.jpg",
    images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-extension-bois-golden.jpg"],
    accroche: "822 m² — 5 min frontière suisse — Quartier calme — CES 0,2 — Grande surface",
    description: [
      "Belle parcelle de 822 m² à Archamps (74160), sur les hauteurs, dans un quartier résidentiel calme. Même secteur que la parcelle de 466 m², avec une surface généreusement plus grande permettant un projet de villa contemporaine avec jardins.",
      "À 5 minutes de la frontière suisse et 20 minutes du centre de Genève et de l'aéroport. Libre constructeur, coefficient d'emprise au sol de 0,20. Les viabilités sont à prévoir, les réseaux étant disponibles à proximité.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "822 m² — surface généreuse pour un grand projet",
      "CES 0,2 — libre constructeur",
      "5 min frontière suisse — 20 min Genève et aéroport",
      "Quartier résidentiel calme sur les hauteurs d'Archamps",
      "Viabilisation à prévoir (réseaux à proximité)",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Archamps (74160) bénéficie d'un accès exceptionnel à Genève et à son aéroport. Ce terrain de 822 m² sur les hauteurs offre de l'espace et du calme dans une commune dynamique du Genevois français. Zone sismique 3 — bureau d'études structure intégré dans tous les projets M&M CONSTRUCTION sur la commune.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-savigny-670m2-pres-colombiers",
    commune: "Savigny",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 670,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 199500,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-maison-bois-montagne-1.jpg"],
    accroche: "670 m² plat viabilisé — Lotissement Les Prés Colombiers — Vue massifs — Permis déposable immédiatement",
    description: [
      "Terrain plat de 670 m² dans le lotissement 'Les Prés Colombiers' à Savigny (74520), composé de 4 lots de 609 à 693 m². Magnifique terrain plat en bordure agricole, offrant une vue dégagée sur les massifs environnants. Terrains viabilisés et libres constructeurs.",
      "Le permis de construire peut être déposé immédiatement. Un environnement naturel préservé, parfait pour les amoureux de nature souhaitant construire dans un cadre authentique tout en restant proche de Genève.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "670 m² plat dans le lotissement Les Prés Colombiers",
      "Vue dégagée sur les massifs environnants",
      "Viabilisé et libre constructeur",
      "Permis de construire déposable immédiatement",
      "Cadre naturel préservé — Savigny (74520)",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Savigny est une commune de Haute-Savoie (74520) offrant un cadre de vie authentique et préservé dans le chef-lieu de commune. Le lotissement Les Prés Colombiers est un projet de 4 lots entièrement viabilisés permettant de construire rapidement. Zone sismique 3 — bureau d'études structure requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-vers-640m2-vue-jet-eau-geneve",
    commune: "Vers",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 640,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 230000,
    statut: "Disponible",
    image: "/images/hero-extension-bois-jardin.jpg",
    images: ["/images/hero-extension-bois-jardin.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "640 m² viabilisé — Vue sur le jet d'eau de Genève — 115 m² au sol — Libre constructeur",
    description: [
      "Terrain entièrement viabilisé de 640 m² à Vers (74160), en limite de village, libre constructeur. La parcelle offre une vue remarquable sur le jet d'eau de Genève, dans un secteur agréable et bucolique.",
      "La possibilité de construire une surface au sol de 115 m² permet d'envisager une belle maison de plain-pied ou un projet à étage. Raccordé à tous les réseaux, y compris à l'égout. À découvrir rapidement dans ce secteur aux opportunités rares.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "640 m² entièrement viabilisé — raccordé à l'égout",
      "Vue sur le jet d'eau de Genève",
      "Surface constructible au sol : 115 m²",
      "Libre constructeur — en limite de village calme",
      "Vers (74160) — Genevois français",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Vers est une commune du Genevois français (74160) offrant un cadre de vie bucolique avec des vues exceptionnelles vers le lac Léman et Genève. Ce type de terrain viabilisé avec vue est une opportunité rare dans ce secteur. Zone sismique 3 — bureau d'études structure requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
  {
    slug: "terrain-dingy-vuache-835m2-hameau-fleur-or",
    commune: "Dingy-en-Vuache",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 835,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 345000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-1.jpg",
    images: ["/images/hero-maison-bois-montagne-1.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "835 m² viabilisé — Le Hameau de la fleur d'Or — Libre constructeur — 30 min Genève",
    description: [
      "Terrain viabilisé de 835 m² dans le lotissement 'Le Hameau de la fleur d'Or' à Dingy-en-Vuache (74520), idéalement situé pour les travailleurs locaux et frontaliers. Raccordé à tous les réseaux et desservi par une voirie principale aménagée. Libre constructeur.",
      "La surface généreuse de cette parcelle permet d'envisager une villa familiale avec de beaux espaces extérieurs. À 30 minutes de Genève et dans un cadre verdoyant et calme typique de la Haute-Savoie.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "835 m² — grande surface dans Le Hameau de la fleur d'Or",
      "Viabilisé — tous réseaux raccordés",
      "Libre constructeur",
      "30 minutes de Genève — cadre verdoyant",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Le lotissement 'Le Hameau de la fleur d'Or' à Dingy-en-Vuache (74520) propose plusieurs lots dont cette grande parcelle de 835 m². Dingy-en-Vuache offre un cadre naturel préservé à distance raisonnable de Genève. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-dingy-vuache-568m2-ces30",
    commune: "Dingy-en-Vuache",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 568,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 240000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-extension-bois-jardin.jpg"],
    accroche: "568 m² — CES 30 % — Emprise 170 m² — Viabilités en bordure — Libre constructeur",
    description: [
      "Parcelle à bâtir de 568 m² à Dingy-en-Vuache (74520), avec un coefficient d'emprise au sol de 30 %, permettant une surface au sol maximale de 170 m². Les viabilités sont disponibles en bordure de terrain — le raccordement est donc réalisable.",
      "Libre constructeur. Cette configuration réglementaire permet d'envisager un projet de maison familiale de belle surface avec des espaces extérieurs bien proportionnés.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "568 m² — CES 30 % — emprise au sol 170 m²",
      "Viabilités en bordure — raccordement possible",
      "Libre constructeur",
      "Dingy-en-Vuache (74520) — Haute-Savoie",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Ce terrain à Dingy-en-Vuache présente l'avantage d'un CES de 30 %, légèrement supérieur à la moyenne du secteur, permettant une emprise au sol généreuse de 170 m² sur 568 m². Les viabilités en bordure facilitent le raccordement. Zone sismique 3 — bureau d'études structure requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
    ],
  },
  {
    slug: "terrain-vulbens-424m2-maison-jumelee",
    commune: "Vulbens",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 424,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 235000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "424 m² plat viabilisé — Maison jumelée 250 m² SP — Lotissement — Vulbens (74520)",
    description: [
      "Lot de 424 m² dans un lotissement à Vulbens (74520), terrain plat et entièrement viabilisé. La configuration réglementaire du lotissement est prévue pour une maison jumelée avec une surface de plancher autorisée de 250 m² — idéale pour un projet en duo ou une famille cherchant un grand espace habitable.",
      "Proche de la frontière suisse, dans un secteur bien desservi par les transports transfrontaliers. Vulbens est une commune calme du Genevois français, très appréciée pour sa qualité de vie.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "424 m² plat et viabilisé dans un lotissement",
      "Maison jumelée — surface de plancher 250 m²",
      "Proche frontière suisse — transports transfrontaliers",
      "Vulbens (74520) — commune calme du Genevois français",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Ce lot de Vulbens (74520) est destiné à une maison jumelée, une formule permettant de réduire le coût foncier à la surface habitable tout en conservant un terrain de 424 m². La commune est idéalement positionnée aux portes de la Suisse. Zone sismique 3.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Maison ossature bois : avantages, coûts et délais", href: "/guides/maison-ossature-bois/" },
    ],
  },
  {
    slug: "terrain-collonges-sous-saleve-1053m2-zone-ud",
    commune: "Collonges-sous-Salève",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 1053,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 572000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-alpine.jpg",
    images: ["/images/hero-maison-bois-alpine.jpg", "/images/hero-maison-bois-montagne-1.jpg"],
    accroche: "1 053 m² zone UD — CES 0,25 — Exposition sud-ouest — Douane 5 min — Genève 20 min",
    description: [
      "Emplacement privilégié pour frontaliers : terrain de 1 053 m² à Collonges-sous-Salève (74160), à quelques minutes de la frontière suisse. Classé en zone UD avec un coefficient d'emprise au sol de 0,25, la parcelle permet un projet résidentiel harmonieux dans un environnement pavillonnaire verdoyant.",
      "Exposition sud-ouest pour un ensoleillement optimal et une belle vue dégagée sur les alentours. Les raccordements aux réseaux sont accessibles en bordure de parcelle. Douane de Croix-de-Rozon à 5 minutes, Genève accessible en 20 minutes. Les commerces, écoles et services se trouvent à proximité immédiate.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. Informations non contractuelles.",
    ],
    points: [
      "1 053 m² — zone UD — CES 0,25",
      "Exposition sud-ouest — belle vue dégagée",
      "Raccordements en bordure de parcelle",
      "Douane Croix-de-Rozon à 5 min — Genève à 20 min",
      "Commerces, écoles et services à proximité",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Collonges-sous-Salève (74160) est une commune très prisée des frontaliers, adossée au massif du Salève et à quelques minutes de la frontière suisse. La zone UD avec CES 0,25 permet une emprise au sol d'environ 263 m² sur cette parcelle de 1 053 m², laissant de larges espaces extérieurs. Zone sismique 3 — bureau d'études structure intégré systématiquement par M&M CONSTRUCTION.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
      { titre: "Permis de construire en Genevois français", href: "/guides/permis-construire-genevois/" },
    ],
  },
  {
    slug: "terrain-collonges-sous-saleve-1096m2-vue-leman",
    commune: "Collonges-sous-Salève",
    departement: "Haute-Savoie (74)",
    zone: "Genevois français",
    type: "Terrain à bâtir",
    surfaceTerrain: 1096,
    surfaceHabitable: 0,
    pieces: 0,
    budget: 475000,
    statut: "Disponible",
    image: "/images/hero-maison-bois-montagne-2.jpg",
    images: ["/images/hero-maison-bois-montagne-2.jpg", "/images/hero-maison-bois-alpine.jpg"],
    accroche: "1 096 m² — Vue sur le Jura, le Salève et le Lac Léman — Cadre calme et préservé",
    description: [
      "Terrain de 1 096 m² à Collonges-sous-Salève (74160), offrant une vue dégagée remarquable sur le Jura, le massif du Salève et le Lac Léman. Un panorama exceptionnel dans un environnement calme et préservé.",
      "Collonges-sous-Salève est une commune très appréciée des frontaliers pour la qualité de vie qu'elle offre, à bonne distance de Genève. Une rare opportunité sur ce secteur prisé, aux portes de la Suisse.",
      "Terrain identifié auprès de notre partenaire foncier, sous réserve de disponibilité et d'accord définitif des parties. M&M CONSTRUCTION peut accompagner votre projet depuis l'étude de faisabilité jusqu'à la réception du chantier.",
    ],
    points: [
      "1 096 m² — vue sur Jura, Salève et Lac Léman",
      "Cadre calme et préservé",
      "Collonges-sous-Salève (74160) — portes de la Suisse",
      "Commune très prisée des frontaliers",
      "Terrain sous réserve de disponibilité — partenaire foncier",
    ],
    contexte: "Ce terrain de Collonges-sous-Salève (74160) se distingue par son triple panorama sur le Jura, le Salève et le Lac Léman — une vue d'exception rare dans ce secteur. La commune est l'une des plus recherchées du Genevois français. Zone sismique 3 — bureau d'études structure systématiquement requis.",
    guidesLies: [
      { titre: "Faire construire en Haute-Savoie — guide complet", href: "/faire-construire-haute-savoie/" },
      { titre: "Prix maison ossature bois en Haute-Savoie", href: "/guides/prix-maison-ossature-bois-haute-savoie/" },
    ],
  },
];

export function getAnnonce(slug: string): Annonce | undefined {
  return annonces.find((a) => a.slug === slug);
}

export function getAutresAnnonces(slug: string): Annonce[] {
  const current = annonces.find((a) => a.slug === slug);
  const others = annonces.filter((a) => a.slug !== slug);
  if (!current) return others.slice(0, 3);
  const sameZoneAndType = others.filter((a) => a.zone === current.zone && a.type === current.type);
  const sameZone = others.filter((a) => a.zone === current.zone && a.type !== current.type);
  const rest = others.filter((a) => a.zone !== current.zone);
  return [...sameZoneAndType, ...sameZone, ...rest].slice(0, 3);
}
